// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/billing.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
import { PaymentMethodGateway } from "./payments";
import { PaymentMethodItem } from "./payments";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetPaymentMethodsResponse
 */
export interface GetPaymentMethodsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.PaymentMethodItem items = 1
     */
    items: PaymentMethodItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetPaymentMethodRequest
 */
export interface GetPaymentMethodRequest {
    /**
     * @generated from protobuf field: string paymentMethodId = 1
     */
    paymentMethodId: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2
     */
    paymentGateway: PaymentMethodGateway;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetPaymentMethodResponse
 */
export interface GetPaymentMethodResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodItem item = 1
     */
    item?: PaymentMethodItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest
 */
export interface AddPaymentMethodRequest {
    /**
     * @generated from protobuf oneof: paymentMethod
     */
    paymentMethod: {
        oneofKind: "stripe";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod stripe = 1
         */
        stripe: AddPaymentMethodRequest_AddStripePaymentMethod;
    } | {
        oneofKind: "braintree";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod braintree = 2
         */
        braintree: AddPaymentMethodRequest_AddBraintreePaymentMethod;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod
 */
export interface AddPaymentMethodRequest_AddStripePaymentMethod {
    /**
     * @generated from protobuf field: google.protobuf.StringValue idempotencyKey = 1
     */
    idempotencyKey?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod
 */
export interface AddPaymentMethodRequest_AddBraintreePaymentMethod {
    /**
     * @generated from protobuf field: google.protobuf.StringValue nonce = 1
     */
    nonce?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue deviceData = 2
     */
    deviceData?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse
 */
export interface AddPaymentMethodResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
    /**
     * @generated from protobuf oneof: gatewayResponse
     */
    gatewayResponse: {
        oneofKind: "stripe";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse stripe = 2
         */
        stripe: AddPaymentMethodResponse_StripeGatewayResponse;
    } | {
        oneofKind: "braintree";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse braintree = 3
         */
        braintree: AddPaymentMethodResponse_BraintreeGatewayResponse;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodItem paymentMethodItem = 4
     */
    paymentMethodItem?: PaymentMethodItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse
 */
export interface AddPaymentMethodResponse_StripeGatewayResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse
 */
export interface AddPaymentMethodResponse_BraintreeGatewayResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.DeletePaymentMethodRequest
 */
export interface DeletePaymentMethodRequest {
    /**
     * @generated from protobuf field: string paymentMethodId = 1
     */
    paymentMethodId: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2
     */
    paymentGateway: PaymentMethodGateway;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.DeletePaymentMethodResponse
 */
export interface DeletePaymentMethodResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SetDefaultPaymentMethodRequest
 */
export interface SetDefaultPaymentMethodRequest {
    /**
     * @generated from protobuf field: string paymentMethodId = 1
     */
    paymentMethodId: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2
     */
    paymentGateway: PaymentMethodGateway;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SetDefaultPaymentMethodResponse
 */
export interface SetDefaultPaymentMethodResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetGatewayTokenRequest
 */
export interface GetGatewayTokenRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodGateway gateway = 1
     */
    gateway: PaymentMethodGateway;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetGatewayTokenRequest.GatewayTokenType tokenType = 2
     */
    tokenType: GetGatewayTokenRequest_GatewayTokenType;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetGatewayTokenRequest.GatewayTokenType
 */
export enum GetGatewayTokenRequest_GatewayTokenType {
    /**
     * @generated from protobuf enum value: Default = 0;
     */
    Default = 0,
    /**
     * @generated from protobuf enum value: AddPaymentMethod = 1;
     */
    AddPaymentMethod = 1,
    /**
     * @generated from protobuf enum value: Checkout = 2;
     */
    Checkout = 2
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetGatewayTokenResponse
 */
export interface GetGatewayTokenResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
    /**
     * @generated from protobuf field: google.protobuf.StringValue token = 2
     */
    token?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.BillingPeriod
 */
export interface BillingPeriod {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp periodStart = 1
     */
    periodStart?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp periodEnd = 2
     */
    periodEnd?: Timestamp;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetPaymentMethodsResponse$Type extends MessageType<GetPaymentMethodsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetPaymentMethodsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PaymentMethodItem }
        ]);
    }
    create(value?: PartialMessage<GetPaymentMethodsResponse>): GetPaymentMethodsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetPaymentMethodsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPaymentMethodsResponse): GetPaymentMethodsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.PaymentMethodItem items */ 1:
                    message.items.push(PaymentMethodItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPaymentMethodsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.PaymentMethodItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            PaymentMethodItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetPaymentMethodsResponse
 */
export const GetPaymentMethodsResponse = new GetPaymentMethodsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPaymentMethodRequest$Type extends MessageType<GetPaymentMethodRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetPaymentMethodRequest", [
            { no: 1, name: "paymentMethodId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "paymentGateway", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodGateway", PaymentMethodGateway] }
        ]);
    }
    create(value?: PartialMessage<GetPaymentMethodRequest>): GetPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentMethodId = "";
        message.paymentGateway = 0;
        if (value !== undefined)
            reflectionMergePartial<GetPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPaymentMethodRequest): GetPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string paymentMethodId */ 1:
                    message.paymentMethodId = reader.string();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway */ 2:
                    message.paymentGateway = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string paymentMethodId = 1; */
        if (message.paymentMethodId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentMethodId);
        /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2; */
        if (message.paymentGateway !== 0)
            writer.tag(2, WireType.Varint).int32(message.paymentGateway);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetPaymentMethodRequest
 */
export const GetPaymentMethodRequest = new GetPaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPaymentMethodResponse$Type extends MessageType<GetPaymentMethodResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetPaymentMethodResponse", [
            { no: 1, name: "item", kind: "message", T: () => PaymentMethodItem }
        ]);
    }
    create(value?: PartialMessage<GetPaymentMethodResponse>): GetPaymentMethodResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPaymentMethodResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPaymentMethodResponse): GetPaymentMethodResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.PaymentMethodItem item */ 1:
                    message.item = PaymentMethodItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPaymentMethodResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.PaymentMethodItem item = 1; */
        if (message.item)
            PaymentMethodItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetPaymentMethodResponse
 */
export const GetPaymentMethodResponse = new GetPaymentMethodResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodRequest$Type extends MessageType<AddPaymentMethodRequest> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodRequest", [
            { no: 1, name: "stripe", kind: "message", oneof: "paymentMethod", T: () => AddPaymentMethodRequest_AddStripePaymentMethod },
            { no: 2, name: "braintree", kind: "message", oneof: "paymentMethod", T: () => AddPaymentMethodRequest_AddBraintreePaymentMethod }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodRequest>): AddPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentMethod = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodRequest): AddPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod stripe */ 1:
                    message.paymentMethod = {
                        oneofKind: "stripe",
                        stripe: AddPaymentMethodRequest_AddStripePaymentMethod.internalBinaryRead(reader, reader.uint32(), options, (message.paymentMethod as any).stripe)
                    };
                    break;
                case /* wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod braintree */ 2:
                    message.paymentMethod = {
                        oneofKind: "braintree",
                        braintree: AddPaymentMethodRequest_AddBraintreePaymentMethod.internalBinaryRead(reader, reader.uint32(), options, (message.paymentMethod as any).braintree)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod stripe = 1; */
        if (message.paymentMethod.oneofKind === "stripe")
            AddPaymentMethodRequest_AddStripePaymentMethod.internalBinaryWrite(message.paymentMethod.stripe, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod braintree = 2; */
        if (message.paymentMethod.oneofKind === "braintree")
            AddPaymentMethodRequest_AddBraintreePaymentMethod.internalBinaryWrite(message.paymentMethod.braintree, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest
 */
export const AddPaymentMethodRequest = new AddPaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodRequest_AddStripePaymentMethod$Type extends MessageType<AddPaymentMethodRequest_AddStripePaymentMethod> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod", [
            { no: 1, name: "idempotencyKey", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodRequest_AddStripePaymentMethod>): AddPaymentMethodRequest_AddStripePaymentMethod {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodRequest_AddStripePaymentMethod>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodRequest_AddStripePaymentMethod): AddPaymentMethodRequest_AddStripePaymentMethod {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue idempotencyKey */ 1:
                    message.idempotencyKey = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.idempotencyKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodRequest_AddStripePaymentMethod, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue idempotencyKey = 1; */
        if (message.idempotencyKey)
            StringValue.internalBinaryWrite(message.idempotencyKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest.AddStripePaymentMethod
 */
export const AddPaymentMethodRequest_AddStripePaymentMethod = new AddPaymentMethodRequest_AddStripePaymentMethod$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodRequest_AddBraintreePaymentMethod$Type extends MessageType<AddPaymentMethodRequest_AddBraintreePaymentMethod> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod", [
            { no: 1, name: "nonce", kind: "message", T: () => StringValue },
            { no: 2, name: "deviceData", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodRequest_AddBraintreePaymentMethod>): AddPaymentMethodRequest_AddBraintreePaymentMethod {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodRequest_AddBraintreePaymentMethod>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodRequest_AddBraintreePaymentMethod): AddPaymentMethodRequest_AddBraintreePaymentMethod {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue nonce */ 1:
                    message.nonce = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.nonce);
                    break;
                case /* google.protobuf.StringValue deviceData */ 2:
                    message.deviceData = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.deviceData);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodRequest_AddBraintreePaymentMethod, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue nonce = 1; */
        if (message.nonce)
            StringValue.internalBinaryWrite(message.nonce, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue deviceData = 2; */
        if (message.deviceData)
            StringValue.internalBinaryWrite(message.deviceData, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodRequest.AddBraintreePaymentMethod
 */
export const AddPaymentMethodRequest_AddBraintreePaymentMethod = new AddPaymentMethodRequest_AddBraintreePaymentMethod$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodResponse$Type extends MessageType<AddPaymentMethodResponse> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "stripe", kind: "message", oneof: "gatewayResponse", T: () => AddPaymentMethodResponse_StripeGatewayResponse },
            { no: 3, name: "braintree", kind: "message", oneof: "gatewayResponse", T: () => AddPaymentMethodResponse_BraintreeGatewayResponse },
            { no: 4, name: "paymentMethodItem", kind: "message", T: () => PaymentMethodItem }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodResponse>): AddPaymentMethodResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        message.gatewayResponse = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodResponse): AddPaymentMethodResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse stripe */ 2:
                    message.gatewayResponse = {
                        oneofKind: "stripe",
                        stripe: AddPaymentMethodResponse_StripeGatewayResponse.internalBinaryRead(reader, reader.uint32(), options, (message.gatewayResponse as any).stripe)
                    };
                    break;
                case /* wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse braintree */ 3:
                    message.gatewayResponse = {
                        oneofKind: "braintree",
                        braintree: AddPaymentMethodResponse_BraintreeGatewayResponse.internalBinaryRead(reader, reader.uint32(), options, (message.gatewayResponse as any).braintree)
                    };
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodItem paymentMethodItem */ 4:
                    message.paymentMethodItem = PaymentMethodItem.internalBinaryRead(reader, reader.uint32(), options, message.paymentMethodItem);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        /* wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse stripe = 2; */
        if (message.gatewayResponse.oneofKind === "stripe")
            AddPaymentMethodResponse_StripeGatewayResponse.internalBinaryWrite(message.gatewayResponse.stripe, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse braintree = 3; */
        if (message.gatewayResponse.oneofKind === "braintree")
            AddPaymentMethodResponse_BraintreeGatewayResponse.internalBinaryWrite(message.gatewayResponse.braintree, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.PaymentMethodItem paymentMethodItem = 4; */
        if (message.paymentMethodItem)
            PaymentMethodItem.internalBinaryWrite(message.paymentMethodItem, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse
 */
export const AddPaymentMethodResponse = new AddPaymentMethodResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodResponse_StripeGatewayResponse$Type extends MessageType<AddPaymentMethodResponse_StripeGatewayResponse> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodResponse_StripeGatewayResponse>): AddPaymentMethodResponse_StripeGatewayResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodResponse_StripeGatewayResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodResponse_StripeGatewayResponse): AddPaymentMethodResponse_StripeGatewayResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodResponse_StripeGatewayResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse.StripeGatewayResponse
 */
export const AddPaymentMethodResponse_StripeGatewayResponse = new AddPaymentMethodResponse_StripeGatewayResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPaymentMethodResponse_BraintreeGatewayResponse$Type extends MessageType<AddPaymentMethodResponse_BraintreeGatewayResponse> {
    constructor() {
        super("wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AddPaymentMethodResponse_BraintreeGatewayResponse>): AddPaymentMethodResponse_BraintreeGatewayResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<AddPaymentMethodResponse_BraintreeGatewayResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPaymentMethodResponse_BraintreeGatewayResponse): AddPaymentMethodResponse_BraintreeGatewayResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPaymentMethodResponse_BraintreeGatewayResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddPaymentMethodResponse.BraintreeGatewayResponse
 */
export const AddPaymentMethodResponse_BraintreeGatewayResponse = new AddPaymentMethodResponse_BraintreeGatewayResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePaymentMethodRequest$Type extends MessageType<DeletePaymentMethodRequest> {
    constructor() {
        super("wuxiaworld.api.v2.DeletePaymentMethodRequest", [
            { no: 1, name: "paymentMethodId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "paymentGateway", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodGateway", PaymentMethodGateway] }
        ]);
    }
    create(value?: PartialMessage<DeletePaymentMethodRequest>): DeletePaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentMethodId = "";
        message.paymentGateway = 0;
        if (value !== undefined)
            reflectionMergePartial<DeletePaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePaymentMethodRequest): DeletePaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string paymentMethodId */ 1:
                    message.paymentMethodId = reader.string();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway */ 2:
                    message.paymentGateway = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string paymentMethodId = 1; */
        if (message.paymentMethodId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentMethodId);
        /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2; */
        if (message.paymentGateway !== 0)
            writer.tag(2, WireType.Varint).int32(message.paymentGateway);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.DeletePaymentMethodRequest
 */
export const DeletePaymentMethodRequest = new DeletePaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeletePaymentMethodResponse$Type extends MessageType<DeletePaymentMethodResponse> {
    constructor() {
        super("wuxiaworld.api.v2.DeletePaymentMethodResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeletePaymentMethodResponse>): DeletePaymentMethodResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<DeletePaymentMethodResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeletePaymentMethodResponse): DeletePaymentMethodResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeletePaymentMethodResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.DeletePaymentMethodResponse
 */
export const DeletePaymentMethodResponse = new DeletePaymentMethodResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetDefaultPaymentMethodRequest$Type extends MessageType<SetDefaultPaymentMethodRequest> {
    constructor() {
        super("wuxiaworld.api.v2.SetDefaultPaymentMethodRequest", [
            { no: 1, name: "paymentMethodId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "paymentGateway", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodGateway", PaymentMethodGateway] }
        ]);
    }
    create(value?: PartialMessage<SetDefaultPaymentMethodRequest>): SetDefaultPaymentMethodRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentMethodId = "";
        message.paymentGateway = 0;
        if (value !== undefined)
            reflectionMergePartial<SetDefaultPaymentMethodRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetDefaultPaymentMethodRequest): SetDefaultPaymentMethodRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string paymentMethodId */ 1:
                    message.paymentMethodId = reader.string();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway */ 2:
                    message.paymentGateway = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetDefaultPaymentMethodRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string paymentMethodId = 1; */
        if (message.paymentMethodId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentMethodId);
        /* wuxiaworld.api.v2.PaymentMethodGateway paymentGateway = 2; */
        if (message.paymentGateway !== 0)
            writer.tag(2, WireType.Varint).int32(message.paymentGateway);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SetDefaultPaymentMethodRequest
 */
export const SetDefaultPaymentMethodRequest = new SetDefaultPaymentMethodRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetDefaultPaymentMethodResponse$Type extends MessageType<SetDefaultPaymentMethodResponse> {
    constructor() {
        super("wuxiaworld.api.v2.SetDefaultPaymentMethodResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SetDefaultPaymentMethodResponse>): SetDefaultPaymentMethodResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<SetDefaultPaymentMethodResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetDefaultPaymentMethodResponse): SetDefaultPaymentMethodResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetDefaultPaymentMethodResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SetDefaultPaymentMethodResponse
 */
export const SetDefaultPaymentMethodResponse = new SetDefaultPaymentMethodResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetGatewayTokenRequest$Type extends MessageType<GetGatewayTokenRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetGatewayTokenRequest", [
            { no: 1, name: "gateway", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodGateway", PaymentMethodGateway] },
            { no: 2, name: "tokenType", kind: "enum", T: () => ["wuxiaworld.api.v2.GetGatewayTokenRequest.GatewayTokenType", GetGatewayTokenRequest_GatewayTokenType] }
        ]);
    }
    create(value?: PartialMessage<GetGatewayTokenRequest>): GetGatewayTokenRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.gateway = 0;
        message.tokenType = 0;
        if (value !== undefined)
            reflectionMergePartial<GetGatewayTokenRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetGatewayTokenRequest): GetGatewayTokenRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.PaymentMethodGateway gateway */ 1:
                    message.gateway = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.GetGatewayTokenRequest.GatewayTokenType tokenType */ 2:
                    message.tokenType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetGatewayTokenRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.PaymentMethodGateway gateway = 1; */
        if (message.gateway !== 0)
            writer.tag(1, WireType.Varint).int32(message.gateway);
        /* wuxiaworld.api.v2.GetGatewayTokenRequest.GatewayTokenType tokenType = 2; */
        if (message.tokenType !== 0)
            writer.tag(2, WireType.Varint).int32(message.tokenType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetGatewayTokenRequest
 */
export const GetGatewayTokenRequest = new GetGatewayTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetGatewayTokenResponse$Type extends MessageType<GetGatewayTokenResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetGatewayTokenResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "token", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetGatewayTokenResponse>): GetGatewayTokenResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<GetGatewayTokenResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetGatewayTokenResponse): GetGatewayTokenResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                case /* google.protobuf.StringValue token */ 2:
                    message.token = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.token);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetGatewayTokenResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        /* google.protobuf.StringValue token = 2; */
        if (message.token)
            StringValue.internalBinaryWrite(message.token, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetGatewayTokenResponse
 */
export const GetGatewayTokenResponse = new GetGatewayTokenResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BillingPeriod$Type extends MessageType<BillingPeriod> {
    constructor() {
        super("wuxiaworld.api.v2.BillingPeriod", [
            { no: 1, name: "periodStart", kind: "message", T: () => Timestamp },
            { no: 2, name: "periodEnd", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<BillingPeriod>): BillingPeriod {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<BillingPeriod>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BillingPeriod): BillingPeriod {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp periodStart */ 1:
                    message.periodStart = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.periodStart);
                    break;
                case /* google.protobuf.Timestamp periodEnd */ 2:
                    message.periodEnd = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.periodEnd);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BillingPeriod, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp periodStart = 1; */
        if (message.periodStart)
            Timestamp.internalBinaryWrite(message.periodStart, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp periodEnd = 2; */
        if (message.periodEnd)
            Timestamp.internalBinaryWrite(message.periodEnd, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.BillingPeriod
 */
export const BillingPeriod = new BillingPeriod$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Billing
 */
export const Billing = new ServiceType("wuxiaworld.api.v2.Billing", [
    { name: "GetPaymentMethods", options: {}, I: Empty, O: GetPaymentMethodsResponse },
    { name: "GetPaymentMethod", options: {}, I: GetPaymentMethodRequest, O: GetPaymentMethodResponse },
    { name: "AddPaymentMethod", options: {}, I: AddPaymentMethodRequest, O: AddPaymentMethodResponse },
    { name: "DeletePaymentMethod", options: {}, I: DeletePaymentMethodRequest, O: DeletePaymentMethodResponse },
    { name: "SetDefaultPaymentMethod", options: {}, I: SetDefaultPaymentMethodRequest, O: SetDefaultPaymentMethodResponse },
    { name: "GetGatewayToken", options: {}, I: GetGatewayTokenRequest, O: GetGatewayTokenResponse }
]);
