// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/chapter_paragraphs.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message GetChapterParagraphRequest
 */
export interface GetChapterParagraphRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message GetChapterParagraphResponse
 */
export interface GetChapterParagraphResponse {
    /**
     * @generated from protobuf field: ChapterParagraph item = 1
     */
    item?: ChapterParagraph;
}
/**
 * @generated from protobuf message ChapterParagraph
 */
export interface ChapterParagraph {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: int32 chapterId = 2
     */
    chapterId: number;
    /**
     * @generated from protobuf field: int32 totalComments = 3
     */
    totalComments: number;
    /**
     * @generated from protobuf field: google.protobuf.StringValue content = 4
     */
    content?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetChapterParagraphRequest$Type extends MessageType<GetChapterParagraphRequest> {
    constructor() {
        super("GetChapterParagraphRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetChapterParagraphRequest>): GetChapterParagraphRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<GetChapterParagraphRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChapterParagraphRequest): GetChapterParagraphRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChapterParagraphRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GetChapterParagraphRequest
 */
export const GetChapterParagraphRequest = new GetChapterParagraphRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChapterParagraphResponse$Type extends MessageType<GetChapterParagraphResponse> {
    constructor() {
        super("GetChapterParagraphResponse", [
            { no: 1, name: "item", kind: "message", T: () => ChapterParagraph }
        ]);
    }
    create(value?: PartialMessage<GetChapterParagraphResponse>): GetChapterParagraphResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetChapterParagraphResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChapterParagraphResponse): GetChapterParagraphResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ChapterParagraph item */ 1:
                    message.item = ChapterParagraph.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChapterParagraphResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ChapterParagraph item = 1; */
        if (message.item)
            ChapterParagraph.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GetChapterParagraphResponse
 */
export const GetChapterParagraphResponse = new GetChapterParagraphResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChapterParagraph$Type extends MessageType<ChapterParagraph> {
    constructor() {
        super("ChapterParagraph", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "chapterId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "totalComments", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "content", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ChapterParagraph>): ChapterParagraph {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.chapterId = 0;
        message.totalComments = 0;
        if (value !== undefined)
            reflectionMergePartial<ChapterParagraph>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChapterParagraph): ChapterParagraph {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* int32 chapterId */ 2:
                    message.chapterId = reader.int32();
                    break;
                case /* int32 totalComments */ 3:
                    message.totalComments = reader.int32();
                    break;
                case /* google.protobuf.StringValue content */ 4:
                    message.content = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.content);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChapterParagraph, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* int32 chapterId = 2; */
        if (message.chapterId !== 0)
            writer.tag(2, WireType.Varint).int32(message.chapterId);
        /* int32 totalComments = 3; */
        if (message.totalComments !== 0)
            writer.tag(3, WireType.Varint).int32(message.totalComments);
        /* google.protobuf.StringValue content = 4; */
        if (message.content)
            StringValue.internalBinaryWrite(message.content, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ChapterParagraph
 */
export const ChapterParagraph = new ChapterParagraph$Type();
/**
 * @generated ServiceType for protobuf service ChapterParagraphs
 */
export const ChapterParagraphs = new ServiceType("ChapterParagraphs", [
    { name: "GetChapterParagraph", options: {}, I: GetChapterParagraphRequest, O: GetChapterParagraphResponse }
]);
