// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/custom_pages.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { NovelInfo } from "./novels";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetCustomPageRequest
 */
export interface GetCustomPageRequest {
    /**
     * @generated from protobuf oneof: selector
     */
    selector: {
        oneofKind: "id";
        /**
         * @generated from protobuf field: int32 id = 1
         */
        id: number;
    } | {
        oneofKind: "slug";
        /**
         * @generated from protobuf field: string slug = 2
         */
        slug: string;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector novelSelector = 3
     */
    novelSelector?: GetCustomPageRequest_NovelSelector;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector
 */
export interface GetCustomPageRequest_NovelSelector {
    /**
     * @generated from protobuf oneof: selector
     */
    selector: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 1
         */
        novelId: number;
    } | {
        oneofKind: "novelSlug";
        /**
         * @generated from protobuf field: string novelSlug = 2
         */
        novelSlug: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetCustomPageResponse
 */
export interface GetCustomPageResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.CustomPageItem item = 1
     */
    item?: CustomPageItem;
    /**
     * @generated from protobuf field: bool result = 2
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CustomPageItem
 */
export interface CustomPageItem {
    /**
     * @generated from protobuf field: int32 entityId = 1
     */
    entityId: number;
    /**
     * @generated from protobuf field: string slug = 2
     */
    slug: string;
    /**
     * @generated from protobuf field: string content = 3
     */
    content: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp lastEditedAt = 4
     */
    lastEditedAt?: Timestamp;
    /**
     * @generated from protobuf field: string title = 5
     */
    title: string;
    /**
     * @generated from protobuf field: bool staffOnly = 6
     */
    staffOnly: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp publishedAt = 7
     */
    publishedAt?: Timestamp;
    /**
     * @generated from protobuf field: bool visible = 8
     */
    visible: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.NovelInfo novelInfo = 9
     */
    novelInfo?: NovelInfo;
    /**
     * @generated from protobuf field: bool allowComments = 10
     */
    allowComments: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetCustomPageRequest$Type extends MessageType<GetCustomPageRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetCustomPageRequest", [
            { no: 1, name: "id", kind: "scalar", oneof: "selector", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "slug", kind: "scalar", oneof: "selector", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "novelSelector", kind: "message", T: () => GetCustomPageRequest_NovelSelector }
        ]);
    }
    create(value?: PartialMessage<GetCustomPageRequest>): GetCustomPageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.selector = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<GetCustomPageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCustomPageRequest): GetCustomPageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.selector = {
                        oneofKind: "id",
                        id: reader.int32()
                    };
                    break;
                case /* string slug */ 2:
                    message.selector = {
                        oneofKind: "slug",
                        slug: reader.string()
                    };
                    break;
                case /* wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector novelSelector */ 3:
                    message.novelSelector = GetCustomPageRequest_NovelSelector.internalBinaryRead(reader, reader.uint32(), options, message.novelSelector);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCustomPageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.selector.oneofKind === "id")
            writer.tag(1, WireType.Varint).int32(message.selector.id);
        /* string slug = 2; */
        if (message.selector.oneofKind === "slug")
            writer.tag(2, WireType.LengthDelimited).string(message.selector.slug);
        /* wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector novelSelector = 3; */
        if (message.novelSelector)
            GetCustomPageRequest_NovelSelector.internalBinaryWrite(message.novelSelector, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetCustomPageRequest
 */
export const GetCustomPageRequest = new GetCustomPageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCustomPageRequest_NovelSelector$Type extends MessageType<GetCustomPageRequest_NovelSelector> {
    constructor() {
        super("wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector", [
            { no: 1, name: "novelId", kind: "scalar", oneof: "selector", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "novelSlug", kind: "scalar", oneof: "selector", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetCustomPageRequest_NovelSelector>): GetCustomPageRequest_NovelSelector {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.selector = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<GetCustomPageRequest_NovelSelector>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCustomPageRequest_NovelSelector): GetCustomPageRequest_NovelSelector {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 novelId */ 1:
                    message.selector = {
                        oneofKind: "novelId",
                        novelId: reader.int32()
                    };
                    break;
                case /* string novelSlug */ 2:
                    message.selector = {
                        oneofKind: "novelSlug",
                        novelSlug: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCustomPageRequest_NovelSelector, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 novelId = 1; */
        if (message.selector.oneofKind === "novelId")
            writer.tag(1, WireType.Varint).int32(message.selector.novelId);
        /* string novelSlug = 2; */
        if (message.selector.oneofKind === "novelSlug")
            writer.tag(2, WireType.LengthDelimited).string(message.selector.novelSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetCustomPageRequest.NovelSelector
 */
export const GetCustomPageRequest_NovelSelector = new GetCustomPageRequest_NovelSelector$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCustomPageResponse$Type extends MessageType<GetCustomPageResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetCustomPageResponse", [
            { no: 1, name: "item", kind: "message", T: () => CustomPageItem },
            { no: 2, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GetCustomPageResponse>): GetCustomPageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<GetCustomPageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCustomPageResponse): GetCustomPageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.CustomPageItem item */ 1:
                    message.item = CustomPageItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                case /* bool result */ 2:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCustomPageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.CustomPageItem item = 1; */
        if (message.item)
            CustomPageItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool result = 2; */
        if (message.result !== false)
            writer.tag(2, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetCustomPageResponse
 */
export const GetCustomPageResponse = new GetCustomPageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CustomPageItem$Type extends MessageType<CustomPageItem> {
    constructor() {
        super("wuxiaworld.api.v2.CustomPageItem", [
            { no: 1, name: "entityId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "lastEditedAt", kind: "message", T: () => Timestamp },
            { no: 5, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "staffOnly", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "publishedAt", kind: "message", T: () => Timestamp },
            { no: 8, name: "visible", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "novelInfo", kind: "message", T: () => NovelInfo },
            { no: 10, name: "allowComments", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CustomPageItem>): CustomPageItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.entityId = 0;
        message.slug = "";
        message.content = "";
        message.title = "";
        message.staffOnly = false;
        message.visible = false;
        message.allowComments = false;
        if (value !== undefined)
            reflectionMergePartial<CustomPageItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CustomPageItem): CustomPageItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 entityId */ 1:
                    message.entityId = reader.int32();
                    break;
                case /* string slug */ 2:
                    message.slug = reader.string();
                    break;
                case /* string content */ 3:
                    message.content = reader.string();
                    break;
                case /* google.protobuf.Timestamp lastEditedAt */ 4:
                    message.lastEditedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.lastEditedAt);
                    break;
                case /* string title */ 5:
                    message.title = reader.string();
                    break;
                case /* bool staffOnly */ 6:
                    message.staffOnly = reader.bool();
                    break;
                case /* google.protobuf.Timestamp publishedAt */ 7:
                    message.publishedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedAt);
                    break;
                case /* bool visible */ 8:
                    message.visible = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.NovelInfo novelInfo */ 9:
                    message.novelInfo = NovelInfo.internalBinaryRead(reader, reader.uint32(), options, message.novelInfo);
                    break;
                case /* bool allowComments */ 10:
                    message.allowComments = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CustomPageItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 entityId = 1; */
        if (message.entityId !== 0)
            writer.tag(1, WireType.Varint).int32(message.entityId);
        /* string slug = 2; */
        if (message.slug !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.slug);
        /* string content = 3; */
        if (message.content !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.content);
        /* google.protobuf.Timestamp lastEditedAt = 4; */
        if (message.lastEditedAt)
            Timestamp.internalBinaryWrite(message.lastEditedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string title = 5; */
        if (message.title !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.title);
        /* bool staffOnly = 6; */
        if (message.staffOnly !== false)
            writer.tag(6, WireType.Varint).bool(message.staffOnly);
        /* google.protobuf.Timestamp publishedAt = 7; */
        if (message.publishedAt)
            Timestamp.internalBinaryWrite(message.publishedAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* bool visible = 8; */
        if (message.visible !== false)
            writer.tag(8, WireType.Varint).bool(message.visible);
        /* wuxiaworld.api.v2.NovelInfo novelInfo = 9; */
        if (message.novelInfo)
            NovelInfo.internalBinaryWrite(message.novelInfo, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* bool allowComments = 10; */
        if (message.allowComments !== false)
            writer.tag(10, WireType.Varint).bool(message.allowComments);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CustomPageItem
 */
export const CustomPageItem = new CustomPageItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.CustomPages
 */
export const CustomPages = new ServiceType("wuxiaworld.api.v2.CustomPages", [
    { name: "GetCustomPage", options: {}, I: GetCustomPageRequest, O: GetCustomPageResponse }
]);
