// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/ebooks.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ProductItem } from "./products";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetEbooksResponse
 */
export interface GetEbooksResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.EbookItem items = 1
     */
    items: EbookItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetEbooksRequest
 */
export interface GetEbooksRequest {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks filters = 1
     */
    filters: GetEbooksRequest_FilterEbooks[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks
 */
export interface GetEbooksRequest_FilterEbooks {
    /**
     * @generated from protobuf oneof: filter
     */
    filter: {
        oneofKind: "novelId";
        /**
         * @generated from protobuf field: int32 novelId = 1
         */
        novelId: number;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyEbooksResponse
 */
export interface GetMyEbooksResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.EbookItem items = 1
     */
    items: EbookItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.EbookItem
 */
export interface EbookItem {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: int32 order = 3
     */
    order: number;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverUrl = 4
     */
    coverUrl?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue description = 5
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp dateCreated = 6
     */
    dateCreated?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductItem product = 7
     */
    product?: ProductItem;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.EbookItem.NovelInfo novelInfo = 8
     */
    novelInfo?: EbookItem_NovelInfo;
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.EbookFile ebookFiles = 9
     */
    ebookFiles: EbookFile[];
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserEbookInfo userEbookInfo = 10
     */
    userEbookInfo?: UserEbookInfo;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.EbookItem.NovelInfo
 */
export interface EbookItem_NovelInfo {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string slug = 3
     */
    slug: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverUrl = 4
     */
    coverUrl?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverBlurHash = 5
     */
    coverBlurHash?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue translatorName = 6
     */
    translatorName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue authorName = 7
     */
    authorName?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.EbookFile
 */
export interface EbookFile {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.EbookFile.FileFormat format = 1
     */
    format: EbookFile_FileFormat;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp addedAt = 2
     */
    addedAt?: Timestamp;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.EbookFile.FileFormat
 */
export enum EbookFile_FileFormat {
    /**
     * @generated from protobuf enum value: Unknown = 0;
     */
    Unknown = 0,
    /**
     * @generated from protobuf enum value: Epub = 1;
     */
    Epub = 1,
    /**
     * @generated from protobuf enum value: Mobi = 2;
     */
    Mobi = 2,
    /**
     * @generated from protobuf enum value: Pdf = 3;
     */
    Pdf = 3
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserEbookInfo
 */
export interface UserEbookInfo {
    /**
     * @generated from protobuf field: bool isConsumed = 1
     */
    isConsumed: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetEbooksResponse$Type extends MessageType<GetEbooksResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetEbooksResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EbookItem }
        ]);
    }
    create(value?: PartialMessage<GetEbooksResponse>): GetEbooksResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetEbooksResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetEbooksResponse): GetEbooksResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.EbookItem items */ 1:
                    message.items.push(EbookItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetEbooksResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.EbookItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            EbookItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetEbooksResponse
 */
export const GetEbooksResponse = new GetEbooksResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetEbooksRequest$Type extends MessageType<GetEbooksRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetEbooksRequest", [
            { no: 1, name: "filters", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetEbooksRequest_FilterEbooks }
        ]);
    }
    create(value?: PartialMessage<GetEbooksRequest>): GetEbooksRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.filters = [];
        if (value !== undefined)
            reflectionMergePartial<GetEbooksRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetEbooksRequest): GetEbooksRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks filters */ 1:
                    message.filters.push(GetEbooksRequest_FilterEbooks.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetEbooksRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks filters = 1; */
        for (let i = 0; i < message.filters.length; i++)
            GetEbooksRequest_FilterEbooks.internalBinaryWrite(message.filters[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetEbooksRequest
 */
export const GetEbooksRequest = new GetEbooksRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetEbooksRequest_FilterEbooks$Type extends MessageType<GetEbooksRequest_FilterEbooks> {
    constructor() {
        super("wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks", [
            { no: 1, name: "novelId", kind: "scalar", oneof: "filter", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetEbooksRequest_FilterEbooks>): GetEbooksRequest_FilterEbooks {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.filter = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<GetEbooksRequest_FilterEbooks>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetEbooksRequest_FilterEbooks): GetEbooksRequest_FilterEbooks {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 novelId */ 1:
                    message.filter = {
                        oneofKind: "novelId",
                        novelId: reader.int32()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetEbooksRequest_FilterEbooks, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 novelId = 1; */
        if (message.filter.oneofKind === "novelId")
            writer.tag(1, WireType.Varint).int32(message.filter.novelId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetEbooksRequest.FilterEbooks
 */
export const GetEbooksRequest_FilterEbooks = new GetEbooksRequest_FilterEbooks$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyEbooksResponse$Type extends MessageType<GetMyEbooksResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyEbooksResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EbookItem }
        ]);
    }
    create(value?: PartialMessage<GetMyEbooksResponse>): GetMyEbooksResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetMyEbooksResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyEbooksResponse): GetMyEbooksResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.EbookItem items */ 1:
                    message.items.push(EbookItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyEbooksResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.EbookItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            EbookItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyEbooksResponse
 */
export const GetMyEbooksResponse = new GetMyEbooksResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EbookItem$Type extends MessageType<EbookItem> {
    constructor() {
        super("wuxiaworld.api.v2.EbookItem", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "coverUrl", kind: "message", T: () => StringValue },
            { no: 5, name: "description", kind: "message", T: () => StringValue },
            { no: 6, name: "dateCreated", kind: "message", T: () => Timestamp },
            { no: 7, name: "product", kind: "message", T: () => ProductItem },
            { no: 8, name: "novelInfo", kind: "message", T: () => EbookItem_NovelInfo },
            { no: 9, name: "ebookFiles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EbookFile },
            { no: 10, name: "userEbookInfo", kind: "message", T: () => UserEbookInfo }
        ]);
    }
    create(value?: PartialMessage<EbookItem>): EbookItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.order = 0;
        message.ebookFiles = [];
        if (value !== undefined)
            reflectionMergePartial<EbookItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EbookItem): EbookItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 order */ 3:
                    message.order = reader.int32();
                    break;
                case /* google.protobuf.StringValue coverUrl */ 4:
                    message.coverUrl = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.coverUrl);
                    break;
                case /* google.protobuf.StringValue description */ 5:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* google.protobuf.Timestamp dateCreated */ 6:
                    message.dateCreated = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.dateCreated);
                    break;
                case /* wuxiaworld.api.v2.ProductItem product */ 7:
                    message.product = ProductItem.internalBinaryRead(reader, reader.uint32(), options, message.product);
                    break;
                case /* wuxiaworld.api.v2.EbookItem.NovelInfo novelInfo */ 8:
                    message.novelInfo = EbookItem_NovelInfo.internalBinaryRead(reader, reader.uint32(), options, message.novelInfo);
                    break;
                case /* repeated wuxiaworld.api.v2.EbookFile ebookFiles */ 9:
                    message.ebookFiles.push(EbookFile.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* wuxiaworld.api.v2.UserEbookInfo userEbookInfo */ 10:
                    message.userEbookInfo = UserEbookInfo.internalBinaryRead(reader, reader.uint32(), options, message.userEbookInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EbookItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 order = 3; */
        if (message.order !== 0)
            writer.tag(3, WireType.Varint).int32(message.order);
        /* google.protobuf.StringValue coverUrl = 4; */
        if (message.coverUrl)
            StringValue.internalBinaryWrite(message.coverUrl, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue description = 5; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp dateCreated = 6; */
        if (message.dateCreated)
            Timestamp.internalBinaryWrite(message.dateCreated, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.ProductItem product = 7; */
        if (message.product)
            ProductItem.internalBinaryWrite(message.product, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.EbookItem.NovelInfo novelInfo = 8; */
        if (message.novelInfo)
            EbookItem_NovelInfo.internalBinaryWrite(message.novelInfo, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.EbookFile ebookFiles = 9; */
        for (let i = 0; i < message.ebookFiles.length; i++)
            EbookFile.internalBinaryWrite(message.ebookFiles[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.UserEbookInfo userEbookInfo = 10; */
        if (message.userEbookInfo)
            UserEbookInfo.internalBinaryWrite(message.userEbookInfo, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.EbookItem
 */
export const EbookItem = new EbookItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EbookItem_NovelInfo$Type extends MessageType<EbookItem_NovelInfo> {
    constructor() {
        super("wuxiaworld.api.v2.EbookItem.NovelInfo", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "coverUrl", kind: "message", T: () => StringValue },
            { no: 5, name: "coverBlurHash", kind: "message", T: () => StringValue },
            { no: 6, name: "translatorName", kind: "message", T: () => StringValue },
            { no: 7, name: "authorName", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<EbookItem_NovelInfo>): EbookItem_NovelInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.slug = "";
        if (value !== undefined)
            reflectionMergePartial<EbookItem_NovelInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EbookItem_NovelInfo): EbookItem_NovelInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string slug */ 3:
                    message.slug = reader.string();
                    break;
                case /* google.protobuf.StringValue coverUrl */ 4:
                    message.coverUrl = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.coverUrl);
                    break;
                case /* google.protobuf.StringValue coverBlurHash */ 5:
                    message.coverBlurHash = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.coverBlurHash);
                    break;
                case /* google.protobuf.StringValue translatorName */ 6:
                    message.translatorName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.translatorName);
                    break;
                case /* google.protobuf.StringValue authorName */ 7:
                    message.authorName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.authorName);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EbookItem_NovelInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string slug = 3; */
        if (message.slug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.slug);
        /* google.protobuf.StringValue coverUrl = 4; */
        if (message.coverUrl)
            StringValue.internalBinaryWrite(message.coverUrl, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue coverBlurHash = 5; */
        if (message.coverBlurHash)
            StringValue.internalBinaryWrite(message.coverBlurHash, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue translatorName = 6; */
        if (message.translatorName)
            StringValue.internalBinaryWrite(message.translatorName, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue authorName = 7; */
        if (message.authorName)
            StringValue.internalBinaryWrite(message.authorName, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.EbookItem.NovelInfo
 */
export const EbookItem_NovelInfo = new EbookItem_NovelInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EbookFile$Type extends MessageType<EbookFile> {
    constructor() {
        super("wuxiaworld.api.v2.EbookFile", [
            { no: 1, name: "format", kind: "enum", T: () => ["wuxiaworld.api.v2.EbookFile.FileFormat", EbookFile_FileFormat] },
            { no: 2, name: "addedAt", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<EbookFile>): EbookFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.format = 0;
        if (value !== undefined)
            reflectionMergePartial<EbookFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EbookFile): EbookFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.EbookFile.FileFormat format */ 1:
                    message.format = reader.int32();
                    break;
                case /* google.protobuf.Timestamp addedAt */ 2:
                    message.addedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.addedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EbookFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.EbookFile.FileFormat format = 1; */
        if (message.format !== 0)
            writer.tag(1, WireType.Varint).int32(message.format);
        /* google.protobuf.Timestamp addedAt = 2; */
        if (message.addedAt)
            Timestamp.internalBinaryWrite(message.addedAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.EbookFile
 */
export const EbookFile = new EbookFile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserEbookInfo$Type extends MessageType<UserEbookInfo> {
    constructor() {
        super("wuxiaworld.api.v2.UserEbookInfo", [
            { no: 1, name: "isConsumed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UserEbookInfo>): UserEbookInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isConsumed = false;
        if (value !== undefined)
            reflectionMergePartial<UserEbookInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserEbookInfo): UserEbookInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool isConsumed */ 1:
                    message.isConsumed = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserEbookInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool isConsumed = 1; */
        if (message.isConsumed !== false)
            writer.tag(1, WireType.Varint).bool(message.isConsumed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserEbookInfo
 */
export const UserEbookInfo = new UserEbookInfo$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Ebooks
 */
export const Ebooks = new ServiceType("wuxiaworld.api.v2.Ebooks", [
    { name: "GetEbooks", options: {}, I: GetEbooksRequest, O: GetEbooksResponse },
    { name: "GetMyEbooks", options: {}, I: Empty, O: GetMyEbooksResponse }
]);
