// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/missions.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { KarmaTransactionItem } from "./karma";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMissionSpecsRequest
 */
export interface GetMissionSpecsRequest {
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMissionSpecsResponse
 */
export interface GetMissionSpecsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.MissionSpec specs = 1
     */
    specs: MissionSpec[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyMissionProgressRequest
 */
export interface GetMyMissionProgressRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 1
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: google.protobuf.StringValue groupKey = 2
     */
    groupKey?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyMissionProgressResponse
 */
export interface GetMyMissionProgressResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.MissionProgress progress = 1
     */
    progress: MissionProgress[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsRequest
 */
export interface GetMyCompletedMissionsRequest {
    /**
     * @generated from protobuf oneof: timeCompleted
     */
    timeCompleted: {
        oneofKind: "today";
        /**
         * @generated from protobuf field: bool today = 1
         */
        today: boolean;
    } | {
        oneofKind: "date";
        /**
         * @generated from protobuf field: google.protobuf.Timestamp date = 2
         */
        date: Timestamp;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsResponse
 */
export interface GetMyCompletedMissionsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.MissionItem items = 1
     */
    items: MissionItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CompleteMissionRequest
 */
export interface CompleteMissionRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 1
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.RewardType rewardType = 2
     */
    rewardType: MissionItem_RewardType;
    /**
     * @generated from protobuf field: google.protobuf.StringValue missionSpecId = 3
     */
    missionSpecId?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue missionGroupKey = 4
     */
    missionGroupKey?: StringValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.CompleteMissionResponse
 */
export interface CompleteMissionResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem item = 1
     */
    item?: MissionItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.MissionItem
 */
export interface MissionItem {
    /**
     * @generated from protobuf field: bool completed = 1
     */
    completed: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp completedAt = 2
     */
    completedAt?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 3
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.RewardType rewardType = 4
     */
    rewardType: MissionItem_RewardType;
    /**
     * @generated from protobuf oneof: rewardItem
     */
    rewardItem: {
        oneofKind: "karma";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.KarmaTransactionItem karma = 5
         */
        karma: KarmaTransactionItem;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.MissionItem.MissionType
 */
export enum MissionItem_MissionType {
    /**
     * @generated from protobuf enum value: MissionTypeNone = 0;
     */
    MissionTypeNone = 0,
    /**
     * @generated from protobuf enum value: MissionTypeCheckIn = 1;
     */
    MissionTypeCheckIn = 1,
    /**
     * @generated from protobuf enum value: MissionTypeComment = 2;
     */
    MissionTypeComment = 2,
    /**
     * @generated from protobuf enum value: MissionTypeRead = 3;
     */
    MissionTypeRead = 3,
    /**
     * @generated from protobuf enum value: MissionTypeEvent = 4;
     */
    MissionTypeEvent = 4
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.MissionItem.MissionScope
 */
export enum MissionItem_MissionScope {
    /**
     * @generated from protobuf enum value: MissionScopeDay = 0;
     */
    MissionScopeDay = 0,
    /**
     * @generated from protobuf enum value: MissionScopeWeek = 1;
     */
    MissionScopeWeek = 1,
    /**
     * @generated from protobuf enum value: MissionScopeMonth = 2;
     */
    MissionScopeMonth = 2,
    /**
     * @generated from protobuf enum value: MissionScopeYear = 3;
     */
    MissionScopeYear = 3,
    /**
     * @generated from protobuf enum value: MissionScopeGlobal = 4;
     */
    MissionScopeGlobal = 4,
    /**
     * @generated from protobuf enum value: MissionScopeNone = -1;
     */
    MissionScopeNone = -1
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.MissionItem.RewardType
 */
export enum MissionItem_RewardType {
    /**
     * @generated from protobuf enum value: RewardTypeNone = 0;
     */
    RewardTypeNone = 0,
    /**
     * @generated from protobuf enum value: RewardTypeKarma = 1;
     */
    RewardTypeKarma = 1,
    /**
     * @generated from protobuf enum value: RewardTypeVoucher = 2;
     */
    RewardTypeVoucher = 2
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.MissionSpec
 */
export interface MissionSpec {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionType missionType = 2
     */
    missionType: MissionItem_MissionType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.RewardType rewardType = 3
     */
    rewardType: MissionItem_RewardType;
    /**
     * @generated from protobuf field: int32 requiredCount = 4
     */
    requiredCount: number;
    /**
     * @generated from protobuf field: int32 rewardAmount = 5
     */
    rewardAmount: number;
    /**
     * @generated from protobuf field: string description = 6
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue shortDescription = 7
     */
    shortDescription?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue groupKey = 8
     */
    groupKey?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue groupLabel = 9
     */
    groupLabel?: StringValue;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionItem.MissionScope missionScope = 10
     */
    missionScope: MissionItem_MissionScope;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.MissionProgress
 */
export interface MissionProgress {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.MissionSpec missionSpec = 1
     */
    missionSpec?: MissionSpec;
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
    /**
     * @generated from protobuf field: bool hasRedeemed = 3
     */
    hasRedeemed: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetMissionSpecsRequest$Type extends MessageType<GetMissionSpecsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetMissionSpecsRequest", []);
    }
    create(value?: PartialMessage<GetMissionSpecsRequest>): GetMissionSpecsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetMissionSpecsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMissionSpecsRequest): GetMissionSpecsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMissionSpecsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMissionSpecsRequest
 */
export const GetMissionSpecsRequest = new GetMissionSpecsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMissionSpecsResponse$Type extends MessageType<GetMissionSpecsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMissionSpecsResponse", [
            { no: 1, name: "specs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MissionSpec }
        ]);
    }
    create(value?: PartialMessage<GetMissionSpecsResponse>): GetMissionSpecsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.specs = [];
        if (value !== undefined)
            reflectionMergePartial<GetMissionSpecsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMissionSpecsResponse): GetMissionSpecsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.MissionSpec specs */ 1:
                    message.specs.push(MissionSpec.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMissionSpecsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.MissionSpec specs = 1; */
        for (let i = 0; i < message.specs.length; i++)
            MissionSpec.internalBinaryWrite(message.specs[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMissionSpecsResponse
 */
export const GetMissionSpecsResponse = new GetMissionSpecsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyMissionProgressRequest$Type extends MessageType<GetMyMissionProgressRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyMissionProgressRequest", [
            { no: 1, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 2, name: "groupKey", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetMyMissionProgressRequest>): GetMyMissionProgressRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.missionType = 0;
        if (value !== undefined)
            reflectionMergePartial<GetMyMissionProgressRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyMissionProgressRequest): GetMyMissionProgressRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.MissionItem.MissionType missionType */ 1:
                    message.missionType = reader.int32();
                    break;
                case /* google.protobuf.StringValue groupKey */ 2:
                    message.groupKey = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.groupKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyMissionProgressRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.MissionItem.MissionType missionType = 1; */
        if (message.missionType !== 0)
            writer.tag(1, WireType.Varint).int32(message.missionType);
        /* google.protobuf.StringValue groupKey = 2; */
        if (message.groupKey)
            StringValue.internalBinaryWrite(message.groupKey, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyMissionProgressRequest
 */
export const GetMyMissionProgressRequest = new GetMyMissionProgressRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyMissionProgressResponse$Type extends MessageType<GetMyMissionProgressResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyMissionProgressResponse", [
            { no: 1, name: "progress", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MissionProgress }
        ]);
    }
    create(value?: PartialMessage<GetMyMissionProgressResponse>): GetMyMissionProgressResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.progress = [];
        if (value !== undefined)
            reflectionMergePartial<GetMyMissionProgressResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyMissionProgressResponse): GetMyMissionProgressResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.MissionProgress progress */ 1:
                    message.progress.push(MissionProgress.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyMissionProgressResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.MissionProgress progress = 1; */
        for (let i = 0; i < message.progress.length; i++)
            MissionProgress.internalBinaryWrite(message.progress[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyMissionProgressResponse
 */
export const GetMyMissionProgressResponse = new GetMyMissionProgressResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyCompletedMissionsRequest$Type extends MessageType<GetMyCompletedMissionsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyCompletedMissionsRequest", [
            { no: 1, name: "today", kind: "scalar", oneof: "timeCompleted", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "date", kind: "message", oneof: "timeCompleted", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<GetMyCompletedMissionsRequest>): GetMyCompletedMissionsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.timeCompleted = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<GetMyCompletedMissionsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyCompletedMissionsRequest): GetMyCompletedMissionsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool today */ 1:
                    message.timeCompleted = {
                        oneofKind: "today",
                        today: reader.bool()
                    };
                    break;
                case /* google.protobuf.Timestamp date */ 2:
                    message.timeCompleted = {
                        oneofKind: "date",
                        date: Timestamp.internalBinaryRead(reader, reader.uint32(), options, (message.timeCompleted as any).date)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyCompletedMissionsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool today = 1; */
        if (message.timeCompleted.oneofKind === "today")
            writer.tag(1, WireType.Varint).bool(message.timeCompleted.today);
        /* google.protobuf.Timestamp date = 2; */
        if (message.timeCompleted.oneofKind === "date")
            Timestamp.internalBinaryWrite(message.timeCompleted.date, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsRequest
 */
export const GetMyCompletedMissionsRequest = new GetMyCompletedMissionsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyCompletedMissionsResponse$Type extends MessageType<GetMyCompletedMissionsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyCompletedMissionsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MissionItem }
        ]);
    }
    create(value?: PartialMessage<GetMyCompletedMissionsResponse>): GetMyCompletedMissionsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetMyCompletedMissionsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyCompletedMissionsResponse): GetMyCompletedMissionsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.MissionItem items */ 1:
                    message.items.push(MissionItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyCompletedMissionsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.MissionItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            MissionItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyCompletedMissionsResponse
 */
export const GetMyCompletedMissionsResponse = new GetMyCompletedMissionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMissionRequest$Type extends MessageType<CompleteMissionRequest> {
    constructor() {
        super("wuxiaworld.api.v2.CompleteMissionRequest", [
            { no: 1, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 2, name: "rewardType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.RewardType", MissionItem_RewardType] },
            { no: 3, name: "missionSpecId", kind: "message", T: () => StringValue },
            { no: 4, name: "missionGroupKey", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<CompleteMissionRequest>): CompleteMissionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.missionType = 0;
        message.rewardType = 0;
        if (value !== undefined)
            reflectionMergePartial<CompleteMissionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteMissionRequest): CompleteMissionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.MissionItem.MissionType missionType */ 1:
                    message.missionType = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.MissionItem.RewardType rewardType */ 2:
                    message.rewardType = reader.int32();
                    break;
                case /* google.protobuf.StringValue missionSpecId */ 3:
                    message.missionSpecId = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.missionSpecId);
                    break;
                case /* google.protobuf.StringValue missionGroupKey */ 4:
                    message.missionGroupKey = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.missionGroupKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteMissionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.MissionItem.MissionType missionType = 1; */
        if (message.missionType !== 0)
            writer.tag(1, WireType.Varint).int32(message.missionType);
        /* wuxiaworld.api.v2.MissionItem.RewardType rewardType = 2; */
        if (message.rewardType !== 0)
            writer.tag(2, WireType.Varint).int32(message.rewardType);
        /* google.protobuf.StringValue missionSpecId = 3; */
        if (message.missionSpecId)
            StringValue.internalBinaryWrite(message.missionSpecId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue missionGroupKey = 4; */
        if (message.missionGroupKey)
            StringValue.internalBinaryWrite(message.missionGroupKey, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CompleteMissionRequest
 */
export const CompleteMissionRequest = new CompleteMissionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMissionResponse$Type extends MessageType<CompleteMissionResponse> {
    constructor() {
        super("wuxiaworld.api.v2.CompleteMissionResponse", [
            { no: 1, name: "item", kind: "message", T: () => MissionItem }
        ]);
    }
    create(value?: PartialMessage<CompleteMissionResponse>): CompleteMissionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CompleteMissionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteMissionResponse): CompleteMissionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.MissionItem item */ 1:
                    message.item = MissionItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteMissionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.MissionItem item = 1; */
        if (message.item)
            MissionItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.CompleteMissionResponse
 */
export const CompleteMissionResponse = new CompleteMissionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MissionItem$Type extends MessageType<MissionItem> {
    constructor() {
        super("wuxiaworld.api.v2.MissionItem", [
            { no: 1, name: "completed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "completedAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 4, name: "rewardType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.RewardType", MissionItem_RewardType] },
            { no: 5, name: "karma", kind: "message", oneof: "rewardItem", T: () => KarmaTransactionItem }
        ]);
    }
    create(value?: PartialMessage<MissionItem>): MissionItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.completed = false;
        message.missionType = 0;
        message.rewardType = 0;
        message.rewardItem = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<MissionItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MissionItem): MissionItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool completed */ 1:
                    message.completed = reader.bool();
                    break;
                case /* google.protobuf.Timestamp completedAt */ 2:
                    message.completedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.completedAt);
                    break;
                case /* wuxiaworld.api.v2.MissionItem.MissionType missionType */ 3:
                    message.missionType = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.MissionItem.RewardType rewardType */ 4:
                    message.rewardType = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.KarmaTransactionItem karma */ 5:
                    message.rewardItem = {
                        oneofKind: "karma",
                        karma: KarmaTransactionItem.internalBinaryRead(reader, reader.uint32(), options, (message.rewardItem as any).karma)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MissionItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool completed = 1; */
        if (message.completed !== false)
            writer.tag(1, WireType.Varint).bool(message.completed);
        /* google.protobuf.Timestamp completedAt = 2; */
        if (message.completedAt)
            Timestamp.internalBinaryWrite(message.completedAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.MissionItem.MissionType missionType = 3; */
        if (message.missionType !== 0)
            writer.tag(3, WireType.Varint).int32(message.missionType);
        /* wuxiaworld.api.v2.MissionItem.RewardType rewardType = 4; */
        if (message.rewardType !== 0)
            writer.tag(4, WireType.Varint).int32(message.rewardType);
        /* wuxiaworld.api.v2.KarmaTransactionItem karma = 5; */
        if (message.rewardItem.oneofKind === "karma")
            KarmaTransactionItem.internalBinaryWrite(message.rewardItem.karma, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.MissionItem
 */
export const MissionItem = new MissionItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MissionSpec$Type extends MessageType<MissionSpec> {
    constructor() {
        super("wuxiaworld.api.v2.MissionSpec", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "missionType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionType", MissionItem_MissionType] },
            { no: 3, name: "rewardType", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.RewardType", MissionItem_RewardType] },
            { no: 4, name: "requiredCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "rewardAmount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "shortDescription", kind: "message", T: () => StringValue },
            { no: 8, name: "groupKey", kind: "message", T: () => StringValue },
            { no: 9, name: "groupLabel", kind: "message", T: () => StringValue },
            { no: 10, name: "missionScope", kind: "enum", T: () => ["wuxiaworld.api.v2.MissionItem.MissionScope", MissionItem_MissionScope] }
        ]);
    }
    create(value?: PartialMessage<MissionSpec>): MissionSpec {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.missionType = 0;
        message.rewardType = 0;
        message.requiredCount = 0;
        message.rewardAmount = 0;
        message.description = "";
        message.missionScope = 0;
        if (value !== undefined)
            reflectionMergePartial<MissionSpec>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MissionSpec): MissionSpec {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* wuxiaworld.api.v2.MissionItem.MissionType missionType */ 2:
                    message.missionType = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.MissionItem.RewardType rewardType */ 3:
                    message.rewardType = reader.int32();
                    break;
                case /* int32 requiredCount */ 4:
                    message.requiredCount = reader.int32();
                    break;
                case /* int32 rewardAmount */ 5:
                    message.rewardAmount = reader.int32();
                    break;
                case /* string description */ 6:
                    message.description = reader.string();
                    break;
                case /* google.protobuf.StringValue shortDescription */ 7:
                    message.shortDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.shortDescription);
                    break;
                case /* google.protobuf.StringValue groupKey */ 8:
                    message.groupKey = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.groupKey);
                    break;
                case /* google.protobuf.StringValue groupLabel */ 9:
                    message.groupLabel = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.groupLabel);
                    break;
                case /* wuxiaworld.api.v2.MissionItem.MissionScope missionScope */ 10:
                    message.missionScope = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MissionSpec, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* wuxiaworld.api.v2.MissionItem.MissionType missionType = 2; */
        if (message.missionType !== 0)
            writer.tag(2, WireType.Varint).int32(message.missionType);
        /* wuxiaworld.api.v2.MissionItem.RewardType rewardType = 3; */
        if (message.rewardType !== 0)
            writer.tag(3, WireType.Varint).int32(message.rewardType);
        /* int32 requiredCount = 4; */
        if (message.requiredCount !== 0)
            writer.tag(4, WireType.Varint).int32(message.requiredCount);
        /* int32 rewardAmount = 5; */
        if (message.rewardAmount !== 0)
            writer.tag(5, WireType.Varint).int32(message.rewardAmount);
        /* string description = 6; */
        if (message.description !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.description);
        /* google.protobuf.StringValue shortDescription = 7; */
        if (message.shortDescription)
            StringValue.internalBinaryWrite(message.shortDescription, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue groupKey = 8; */
        if (message.groupKey)
            StringValue.internalBinaryWrite(message.groupKey, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue groupLabel = 9; */
        if (message.groupLabel)
            StringValue.internalBinaryWrite(message.groupLabel, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.MissionItem.MissionScope missionScope = 10; */
        if (message.missionScope !== 0)
            writer.tag(10, WireType.Varint).int32(message.missionScope);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.MissionSpec
 */
export const MissionSpec = new MissionSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MissionProgress$Type extends MessageType<MissionProgress> {
    constructor() {
        super("wuxiaworld.api.v2.MissionProgress", [
            { no: 1, name: "missionSpec", kind: "message", T: () => MissionSpec },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "hasRedeemed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<MissionProgress>): MissionProgress {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.count = 0;
        message.hasRedeemed = false;
        if (value !== undefined)
            reflectionMergePartial<MissionProgress>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MissionProgress): MissionProgress {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.MissionSpec missionSpec */ 1:
                    message.missionSpec = MissionSpec.internalBinaryRead(reader, reader.uint32(), options, message.missionSpec);
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                case /* bool hasRedeemed */ 3:
                    message.hasRedeemed = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MissionProgress, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.MissionSpec missionSpec = 1; */
        if (message.missionSpec)
            MissionSpec.internalBinaryWrite(message.missionSpec, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        /* bool hasRedeemed = 3; */
        if (message.hasRedeemed !== false)
            writer.tag(3, WireType.Varint).bool(message.hasRedeemed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.MissionProgress
 */
export const MissionProgress = new MissionProgress$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Missions
 */
export const Missions = new ServiceType("wuxiaworld.api.v2.Missions", [
    { name: "GetMissionSpecs", options: {}, I: GetMissionSpecsRequest, O: GetMissionSpecsResponse },
    { name: "GetMyMissionProgress", options: {}, I: GetMyMissionProgressRequest, O: GetMyMissionProgressResponse },
    { name: "GetMyCompletedMissions", options: {}, I: GetMyCompletedMissionsRequest, O: GetMyCompletedMissionsResponse },
    { name: "CompleteMission", options: {}, I: CompleteMissionRequest, O: CompleteMissionResponse }
]);
