// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/pagination.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message wuxiaworld.api.v2.PageInfoRequest
 */
export interface PageInfoRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.PageInfoResponse
 */
export interface PageInfoResponse {
    /**
     * @generated from protobuf field: int32 pageNumber = 1
     */
    pageNumber: number;
    /**
     * @generated from protobuf field: int32 total = 2
     */
    total: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class PageInfoRequest$Type extends MessageType<PageInfoRequest> {
    constructor() {
        super("wuxiaworld.api.v2.PageInfoRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "wuxiaworld.api.v2.required": { value: true }, "wuxiaworld.api.v2.range": { min: { value: 1 } } } },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "wuxiaworld.api.v2.required": { value: true }, "wuxiaworld.api.v2.range": { min: { value: 1 }, max: { value: 100 } } } }
        ]);
    }
    create(value?: PartialMessage<PageInfoRequest>): PageInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<PageInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageInfoRequest): PageInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PageInfoRequest
 */
export const PageInfoRequest = new PageInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageInfoResponse$Type extends MessageType<PageInfoResponse> {
    constructor() {
        super("wuxiaworld.api.v2.PageInfoResponse", [
            { no: 1, name: "pageNumber", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<PageInfoResponse>): PageInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pageNumber = 0;
        message.total = 0;
        if (value !== undefined)
            reflectionMergePartial<PageInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageInfoResponse): PageInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 pageNumber */ 1:
                    message.pageNumber = reader.int32();
                    break;
                case /* int32 total */ 2:
                    message.total = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 pageNumber = 1; */
        if (message.pageNumber !== 0)
            writer.tag(1, WireType.Varint).int32(message.pageNumber);
        /* int32 total = 2; */
        if (message.total !== 0)
            writer.tag(2, WireType.Varint).int32(message.total);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PageInfoResponse
 */
export const PageInfoResponse = new PageInfoResponse$Type();
