// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/payments.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { DecimalValue } from "./types";
import { StringValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.PaymentMethodItem
 */
export interface PaymentMethodItem {
    /**
     * @generated from protobuf field: google.protobuf.StringValue id = 1
     */
    id?: StringValue;
    /**
     * @generated from protobuf field: string fullName = 2
     */
    fullName: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodType type = 3
     */
    type: PaymentMethodType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodGateway gateway = 4
     */
    gateway: PaymentMethodGateway;
    /**
     * @generated from protobuf field: string label = 5
     */
    label: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PaymentMethodItem.CardDetails cardDetails = 6
     */
    cardDetails?: PaymentMethodItem_CardDetails;
    /**
     * @generated from protobuf field: bool isDefault = 7
     */
    isDefault: boolean;
    /**
     * @generated from protobuf field: customTypes.DecimalValue balance = 8
     */
    balance?: DecimalValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.PaymentMethodItem.CardDetails
 */
export interface PaymentMethodItem_CardDetails {
    /**
     * @generated from protobuf field: string brand = 1
     */
    brand: string;
    /**
     * @generated from protobuf field: string last4 = 2
     */
    last4: string;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.PaymentMethodType
 */
export enum PaymentMethodType {
    /**
     * @generated from protobuf enum value: UnknownType = 0;
     */
    UnknownType = 0,
    /**
     * @generated from protobuf enum value: CardType = 1;
     */
    CardType = 1,
    /**
     * @generated from protobuf enum value: PayPalType = 2;
     */
    PayPalType = 2,
    /**
     * @generated from protobuf enum value: KarmaType = 3;
     */
    KarmaType = 3,
    /**
     * @generated from protobuf enum value: SiteCreditsType = 4;
     */
    SiteCreditsType = 4,
    /**
     * @generated from protobuf enum value: EbookVouchersType = 5;
     */
    EbookVouchersType = 5
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.PaymentMethodGateway
 */
export enum PaymentMethodGateway {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: Stripe = 1;
     */
    Stripe = 1,
    /**
     * @generated from protobuf enum value: Braintree = 2;
     */
    Braintree = 2,
    /**
     * @generated from protobuf enum value: Apple = 3;
     */
    Apple = 3,
    /**
     * @generated from protobuf enum value: GooglePlay = 4;
     */
    GooglePlay = 4,
    /**
     * @generated from protobuf enum value: StripeCheckout = 5;
     */
    StripeCheckout = 5,
    /**
     * @generated from protobuf enum value: Wuxiaworld = 6;
     */
    Wuxiaworld = 6,
    /**
     * @generated from protobuf enum value: AppleSK2 = 7;
     */
    AppleSK2 = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class PaymentMethodItem$Type extends MessageType<PaymentMethodItem> {
    constructor() {
        super("wuxiaworld.api.v2.PaymentMethodItem", [
            { no: 1, name: "id", kind: "message", T: () => StringValue },
            { no: 2, name: "fullName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodType", PaymentMethodType] },
            { no: 4, name: "gateway", kind: "enum", T: () => ["wuxiaworld.api.v2.PaymentMethodGateway", PaymentMethodGateway] },
            { no: 5, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "cardDetails", kind: "message", T: () => PaymentMethodItem_CardDetails },
            { no: 7, name: "isDefault", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "balance", kind: "message", T: () => DecimalValue }
        ]);
    }
    create(value?: PartialMessage<PaymentMethodItem>): PaymentMethodItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fullName = "";
        message.type = 0;
        message.gateway = 0;
        message.label = "";
        message.isDefault = false;
        if (value !== undefined)
            reflectionMergePartial<PaymentMethodItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaymentMethodItem): PaymentMethodItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue id */ 1:
                    message.id = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* string fullName */ 2:
                    message.fullName = reader.string();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodGateway gateway */ 4:
                    message.gateway = reader.int32();
                    break;
                case /* string label */ 5:
                    message.label = reader.string();
                    break;
                case /* wuxiaworld.api.v2.PaymentMethodItem.CardDetails cardDetails */ 6:
                    message.cardDetails = PaymentMethodItem_CardDetails.internalBinaryRead(reader, reader.uint32(), options, message.cardDetails);
                    break;
                case /* bool isDefault */ 7:
                    message.isDefault = reader.bool();
                    break;
                case /* customTypes.DecimalValue balance */ 8:
                    message.balance = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.balance);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaymentMethodItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue id = 1; */
        if (message.id)
            StringValue.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string fullName = 2; */
        if (message.fullName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fullName);
        /* wuxiaworld.api.v2.PaymentMethodType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* wuxiaworld.api.v2.PaymentMethodGateway gateway = 4; */
        if (message.gateway !== 0)
            writer.tag(4, WireType.Varint).int32(message.gateway);
        /* string label = 5; */
        if (message.label !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.label);
        /* wuxiaworld.api.v2.PaymentMethodItem.CardDetails cardDetails = 6; */
        if (message.cardDetails)
            PaymentMethodItem_CardDetails.internalBinaryWrite(message.cardDetails, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* bool isDefault = 7; */
        if (message.isDefault !== false)
            writer.tag(7, WireType.Varint).bool(message.isDefault);
        /* customTypes.DecimalValue balance = 8; */
        if (message.balance)
            DecimalValue.internalBinaryWrite(message.balance, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PaymentMethodItem
 */
export const PaymentMethodItem = new PaymentMethodItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaymentMethodItem_CardDetails$Type extends MessageType<PaymentMethodItem_CardDetails> {
    constructor() {
        super("wuxiaworld.api.v2.PaymentMethodItem.CardDetails", [
            { no: 1, name: "brand", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "last4", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PaymentMethodItem_CardDetails>): PaymentMethodItem_CardDetails {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.brand = "";
        message.last4 = "";
        if (value !== undefined)
            reflectionMergePartial<PaymentMethodItem_CardDetails>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaymentMethodItem_CardDetails): PaymentMethodItem_CardDetails {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string brand */ 1:
                    message.brand = reader.string();
                    break;
                case /* string last4 */ 2:
                    message.last4 = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaymentMethodItem_CardDetails, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string brand = 1; */
        if (message.brand !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.brand);
        /* string last4 = 2; */
        if (message.last4 !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.last4);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PaymentMethodItem.CardDetails
 */
export const PaymentMethodItem_CardDetails = new PaymentMethodItem_CardDetails$Type();
