// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/pricing.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../google/protobuf/wrappers";
import { Timestamp } from "../google/protobuf/timestamp";
import { Duration } from "../google/protobuf/duration";
import { DecimalValue } from "./types";
import { Any } from "../google/protobuf/any";
import { Int32Value } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetActivePricingRequest
 */
export interface GetActivePricingRequest {
    /**
     * @generated from protobuf field: int32 seriesId = 1
     */
    seriesId: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetActivePricingResponse
 */
export interface GetActivePricingResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.PricingModel items = 1
     */
    items: PricingModel[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetActivePricingRotationsRequest
 */
export interface GetActivePricingRotationsRequest {
    /**
     * @generated from protobuf field: google.protobuf.Int32Value seriesId = 1
     */
    seriesId?: Int32Value;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetActivePricingRotationsRequest.PricingTypeFilter type = 2
     */
    type: GetActivePricingRotationsRequest_PricingTypeFilter;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetActivePricingRotationsRequest.PricingTypeFilter
 */
export enum GetActivePricingRotationsRequest_PricingTypeFilter {
    /**
     * @generated from protobuf enum value: All = 0;
     */
    All = 0,
    /**
     * @generated from protobuf enum value: Free = 1;
     */
    Free = 1,
    /**
     * @generated from protobuf enum value: Karma = 2;
     */
    Karma = 2,
    /**
     * @generated from protobuf enum value: WaitToUnlock = 3;
     */
    WaitToUnlock = 3
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetActivePricingRotationsResponse
 */
export interface GetActivePricingRotationsResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation items = 1
     */
    items: GetActivePricingRotationsResponse_PricingRotation[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation
 */
export interface GetActivePricingRotationsResponse_PricingRotation {
    /**
     * @generated from protobuf field: google.protobuf.Any object = 1
     */
    object?: Any;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PricingModelRotation rotation = 2
     */
    rotation?: PricingModelRotation;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.FreePricingModel
 */
export interface FreePricingModel {
    /**
     * @generated from protobuf field: customTypes.DecimalValue freeChapters = 1
     */
    freeChapters?: DecimalValue;
    /**
     * @generated from protobuf field: bool requiresLogin = 2
     */
    requiresLogin: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value anonymousChaptersCount = 3
     */
    anonymousChaptersCount?: Int32Value;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.KarmaPricingModel
 */
export interface KarmaPricingModel {
    /**
     * @generated from protobuf field: customTypes.DecimalValue freeChapters = 1
     */
    freeChapters?: DecimalValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.VoucherPricingModel
 */
export interface VoucherPricingModel {
    /**
     * @generated from protobuf field: customTypes.DecimalValue freeChapters = 1
     */
    freeChapters?: DecimalValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.WaitToUnlockPricingModel
 */
export interface WaitToUnlockPricingModel {
    /**
     * @generated from protobuf field: google.protobuf.Duration waitTime = 1
     */
    waitTime?: Duration;
    /**
     * @generated from protobuf field: customTypes.DecimalValue freeChapters = 2
     */
    freeChapters?: DecimalValue;
    /**
     * @generated from protobuf field: int32 lastHoldBack = 3
     */
    lastHoldBack: number;
    /**
     * @generated from protobuf field: int32 unlocksPerWaitTime = 4
     */
    unlocksPerWaitTime: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.PricingModelRotation
 */
export interface PricingModelRotation {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp startTime = 2
     */
    startTime?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp endTime = 3
     */
    endTime?: Timestamp;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.PricingModel
 */
export interface PricingModel {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: int32 seriesId = 2
     */
    seriesId: number;
    /**
     * @generated from protobuf field: bool active = 3
     */
    active: boolean;
    /**
     * @generated from protobuf oneof: pricing
     */
    pricing: {
        oneofKind: "free";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.FreePricingModel free = 4
         */
        free: FreePricingModel;
    } | {
        oneofKind: "karma";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.KarmaPricingModel karma = 5
         */
        karma: KarmaPricingModel;
    } | {
        oneofKind: "waitToUnlock";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.WaitToUnlockPricingModel waitToUnlock = 6
         */
        waitToUnlock: WaitToUnlockPricingModel;
    } | {
        oneofKind: "voucher";
        /**
         * @generated from protobuf field: wuxiaworld.api.v2.VoucherPricingModel voucher = 7
         */
        voucher: VoucherPricingModel;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.PricingModelRotation rotations = 9
     */
    rotations: PricingModelRotation[];
    /**
     * @generated from protobuf field: google.protobuf.StringValue currentRotationId = 10
     */
    currentRotationId?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetActivePricingRequest$Type extends MessageType<GetActivePricingRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetActivePricingRequest", [
            { no: 1, name: "seriesId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetActivePricingRequest>): GetActivePricingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.seriesId = 0;
        if (value !== undefined)
            reflectionMergePartial<GetActivePricingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActivePricingRequest): GetActivePricingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 seriesId */ 1:
                    message.seriesId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActivePricingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 seriesId = 1; */
        if (message.seriesId !== 0)
            writer.tag(1, WireType.Varint).int32(message.seriesId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetActivePricingRequest
 */
export const GetActivePricingRequest = new GetActivePricingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActivePricingResponse$Type extends MessageType<GetActivePricingResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetActivePricingResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PricingModel }
        ]);
    }
    create(value?: PartialMessage<GetActivePricingResponse>): GetActivePricingResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetActivePricingResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActivePricingResponse): GetActivePricingResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.PricingModel items */ 1:
                    message.items.push(PricingModel.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActivePricingResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.PricingModel items = 1; */
        for (let i = 0; i < message.items.length; i++)
            PricingModel.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetActivePricingResponse
 */
export const GetActivePricingResponse = new GetActivePricingResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActivePricingRotationsRequest$Type extends MessageType<GetActivePricingRotationsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetActivePricingRotationsRequest", [
            { no: 1, name: "seriesId", kind: "message", T: () => Int32Value },
            { no: 2, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.GetActivePricingRotationsRequest.PricingTypeFilter", GetActivePricingRotationsRequest_PricingTypeFilter] }
        ]);
    }
    create(value?: PartialMessage<GetActivePricingRotationsRequest>): GetActivePricingRotationsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<GetActivePricingRotationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActivePricingRotationsRequest): GetActivePricingRotationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int32Value seriesId */ 1:
                    message.seriesId = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.seriesId);
                    break;
                case /* wuxiaworld.api.v2.GetActivePricingRotationsRequest.PricingTypeFilter type */ 2:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActivePricingRotationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int32Value seriesId = 1; */
        if (message.seriesId)
            Int32Value.internalBinaryWrite(message.seriesId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.GetActivePricingRotationsRequest.PricingTypeFilter type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetActivePricingRotationsRequest
 */
export const GetActivePricingRotationsRequest = new GetActivePricingRotationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActivePricingRotationsResponse$Type extends MessageType<GetActivePricingRotationsResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetActivePricingRotationsResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetActivePricingRotationsResponse_PricingRotation }
        ]);
    }
    create(value?: PartialMessage<GetActivePricingRotationsResponse>): GetActivePricingRotationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetActivePricingRotationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActivePricingRotationsResponse): GetActivePricingRotationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation items */ 1:
                    message.items.push(GetActivePricingRotationsResponse_PricingRotation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActivePricingRotationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation items = 1; */
        for (let i = 0; i < message.items.length; i++)
            GetActivePricingRotationsResponse_PricingRotation.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetActivePricingRotationsResponse
 */
export const GetActivePricingRotationsResponse = new GetActivePricingRotationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActivePricingRotationsResponse_PricingRotation$Type extends MessageType<GetActivePricingRotationsResponse_PricingRotation> {
    constructor() {
        super("wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation", [
            { no: 1, name: "object", kind: "message", T: () => Any },
            { no: 2, name: "rotation", kind: "message", T: () => PricingModelRotation }
        ]);
    }
    create(value?: PartialMessage<GetActivePricingRotationsResponse_PricingRotation>): GetActivePricingRotationsResponse_PricingRotation {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetActivePricingRotationsResponse_PricingRotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActivePricingRotationsResponse_PricingRotation): GetActivePricingRotationsResponse_PricingRotation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Any object */ 1:
                    message.object = Any.internalBinaryRead(reader, reader.uint32(), options, message.object);
                    break;
                case /* wuxiaworld.api.v2.PricingModelRotation rotation */ 2:
                    message.rotation = PricingModelRotation.internalBinaryRead(reader, reader.uint32(), options, message.rotation);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActivePricingRotationsResponse_PricingRotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Any object = 1; */
        if (message.object)
            Any.internalBinaryWrite(message.object, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.PricingModelRotation rotation = 2; */
        if (message.rotation)
            PricingModelRotation.internalBinaryWrite(message.rotation, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetActivePricingRotationsResponse.PricingRotation
 */
export const GetActivePricingRotationsResponse_PricingRotation = new GetActivePricingRotationsResponse_PricingRotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FreePricingModel$Type extends MessageType<FreePricingModel> {
    constructor() {
        super("wuxiaworld.api.v2.FreePricingModel", [
            { no: 1, name: "freeChapters", kind: "message", T: () => DecimalValue },
            { no: 2, name: "requiresLogin", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "anonymousChaptersCount", kind: "message", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<FreePricingModel>): FreePricingModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requiresLogin = false;
        if (value !== undefined)
            reflectionMergePartial<FreePricingModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FreePricingModel): FreePricingModel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* customTypes.DecimalValue freeChapters */ 1:
                    message.freeChapters = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.freeChapters);
                    break;
                case /* bool requiresLogin */ 2:
                    message.requiresLogin = reader.bool();
                    break;
                case /* google.protobuf.Int32Value anonymousChaptersCount */ 3:
                    message.anonymousChaptersCount = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.anonymousChaptersCount);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FreePricingModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* customTypes.DecimalValue freeChapters = 1; */
        if (message.freeChapters)
            DecimalValue.internalBinaryWrite(message.freeChapters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool requiresLogin = 2; */
        if (message.requiresLogin !== false)
            writer.tag(2, WireType.Varint).bool(message.requiresLogin);
        /* google.protobuf.Int32Value anonymousChaptersCount = 3; */
        if (message.anonymousChaptersCount)
            Int32Value.internalBinaryWrite(message.anonymousChaptersCount, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.FreePricingModel
 */
export const FreePricingModel = new FreePricingModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class KarmaPricingModel$Type extends MessageType<KarmaPricingModel> {
    constructor() {
        super("wuxiaworld.api.v2.KarmaPricingModel", [
            { no: 1, name: "freeChapters", kind: "message", T: () => DecimalValue }
        ]);
    }
    create(value?: PartialMessage<KarmaPricingModel>): KarmaPricingModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<KarmaPricingModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: KarmaPricingModel): KarmaPricingModel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* customTypes.DecimalValue freeChapters */ 1:
                    message.freeChapters = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.freeChapters);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: KarmaPricingModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* customTypes.DecimalValue freeChapters = 1; */
        if (message.freeChapters)
            DecimalValue.internalBinaryWrite(message.freeChapters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.KarmaPricingModel
 */
export const KarmaPricingModel = new KarmaPricingModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VoucherPricingModel$Type extends MessageType<VoucherPricingModel> {
    constructor() {
        super("wuxiaworld.api.v2.VoucherPricingModel", [
            { no: 1, name: "freeChapters", kind: "message", T: () => DecimalValue }
        ]);
    }
    create(value?: PartialMessage<VoucherPricingModel>): VoucherPricingModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<VoucherPricingModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VoucherPricingModel): VoucherPricingModel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* customTypes.DecimalValue freeChapters */ 1:
                    message.freeChapters = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.freeChapters);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VoucherPricingModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* customTypes.DecimalValue freeChapters = 1; */
        if (message.freeChapters)
            DecimalValue.internalBinaryWrite(message.freeChapters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.VoucherPricingModel
 */
export const VoucherPricingModel = new VoucherPricingModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WaitToUnlockPricingModel$Type extends MessageType<WaitToUnlockPricingModel> {
    constructor() {
        super("wuxiaworld.api.v2.WaitToUnlockPricingModel", [
            { no: 1, name: "waitTime", kind: "message", T: () => Duration },
            { no: 2, name: "freeChapters", kind: "message", T: () => DecimalValue },
            { no: 3, name: "lastHoldBack", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "unlocksPerWaitTime", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<WaitToUnlockPricingModel>): WaitToUnlockPricingModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lastHoldBack = 0;
        message.unlocksPerWaitTime = 0;
        if (value !== undefined)
            reflectionMergePartial<WaitToUnlockPricingModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WaitToUnlockPricingModel): WaitToUnlockPricingModel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Duration waitTime */ 1:
                    message.waitTime = Duration.internalBinaryRead(reader, reader.uint32(), options, message.waitTime);
                    break;
                case /* customTypes.DecimalValue freeChapters */ 2:
                    message.freeChapters = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.freeChapters);
                    break;
                case /* int32 lastHoldBack */ 3:
                    message.lastHoldBack = reader.int32();
                    break;
                case /* int32 unlocksPerWaitTime */ 4:
                    message.unlocksPerWaitTime = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WaitToUnlockPricingModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Duration waitTime = 1; */
        if (message.waitTime)
            Duration.internalBinaryWrite(message.waitTime, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* customTypes.DecimalValue freeChapters = 2; */
        if (message.freeChapters)
            DecimalValue.internalBinaryWrite(message.freeChapters, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* int32 lastHoldBack = 3; */
        if (message.lastHoldBack !== 0)
            writer.tag(3, WireType.Varint).int32(message.lastHoldBack);
        /* int32 unlocksPerWaitTime = 4; */
        if (message.unlocksPerWaitTime !== 0)
            writer.tag(4, WireType.Varint).int32(message.unlocksPerWaitTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.WaitToUnlockPricingModel
 */
export const WaitToUnlockPricingModel = new WaitToUnlockPricingModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PricingModelRotation$Type extends MessageType<PricingModelRotation> {
    constructor() {
        super("wuxiaworld.api.v2.PricingModelRotation", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "startTime", kind: "message", T: () => Timestamp },
            { no: 3, name: "endTime", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<PricingModelRotation>): PricingModelRotation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<PricingModelRotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PricingModelRotation): PricingModelRotation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp startTime */ 2:
                    message.startTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.startTime);
                    break;
                case /* google.protobuf.Timestamp endTime */ 3:
                    message.endTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endTime);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PricingModelRotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp startTime = 2; */
        if (message.startTime)
            Timestamp.internalBinaryWrite(message.startTime, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp endTime = 3; */
        if (message.endTime)
            Timestamp.internalBinaryWrite(message.endTime, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PricingModelRotation
 */
export const PricingModelRotation = new PricingModelRotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PricingModel$Type extends MessageType<PricingModel> {
    constructor() {
        super("wuxiaworld.api.v2.PricingModel", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "seriesId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "free", kind: "message", oneof: "pricing", T: () => FreePricingModel },
            { no: 5, name: "karma", kind: "message", oneof: "pricing", T: () => KarmaPricingModel },
            { no: 6, name: "waitToUnlock", kind: "message", oneof: "pricing", T: () => WaitToUnlockPricingModel },
            { no: 7, name: "voucher", kind: "message", oneof: "pricing", T: () => VoucherPricingModel },
            { no: 9, name: "rotations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PricingModelRotation },
            { no: 10, name: "currentRotationId", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<PricingModel>): PricingModel {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.seriesId = 0;
        message.active = false;
        message.pricing = { oneofKind: undefined };
        message.rotations = [];
        if (value !== undefined)
            reflectionMergePartial<PricingModel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PricingModel): PricingModel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 seriesId */ 2:
                    message.seriesId = reader.int32();
                    break;
                case /* bool active */ 3:
                    message.active = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.FreePricingModel free */ 4:
                    message.pricing = {
                        oneofKind: "free",
                        free: FreePricingModel.internalBinaryRead(reader, reader.uint32(), options, (message.pricing as any).free)
                    };
                    break;
                case /* wuxiaworld.api.v2.KarmaPricingModel karma */ 5:
                    message.pricing = {
                        oneofKind: "karma",
                        karma: KarmaPricingModel.internalBinaryRead(reader, reader.uint32(), options, (message.pricing as any).karma)
                    };
                    break;
                case /* wuxiaworld.api.v2.WaitToUnlockPricingModel waitToUnlock */ 6:
                    message.pricing = {
                        oneofKind: "waitToUnlock",
                        waitToUnlock: WaitToUnlockPricingModel.internalBinaryRead(reader, reader.uint32(), options, (message.pricing as any).waitToUnlock)
                    };
                    break;
                case /* wuxiaworld.api.v2.VoucherPricingModel voucher */ 7:
                    message.pricing = {
                        oneofKind: "voucher",
                        voucher: VoucherPricingModel.internalBinaryRead(reader, reader.uint32(), options, (message.pricing as any).voucher)
                    };
                    break;
                case /* repeated wuxiaworld.api.v2.PricingModelRotation rotations */ 9:
                    message.rotations.push(PricingModelRotation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* google.protobuf.StringValue currentRotationId */ 10:
                    message.currentRotationId = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.currentRotationId);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PricingModel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 seriesId = 2; */
        if (message.seriesId !== 0)
            writer.tag(2, WireType.Varint).int32(message.seriesId);
        /* bool active = 3; */
        if (message.active !== false)
            writer.tag(3, WireType.Varint).bool(message.active);
        /* wuxiaworld.api.v2.FreePricingModel free = 4; */
        if (message.pricing.oneofKind === "free")
            FreePricingModel.internalBinaryWrite(message.pricing.free, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.KarmaPricingModel karma = 5; */
        if (message.pricing.oneofKind === "karma")
            KarmaPricingModel.internalBinaryWrite(message.pricing.karma, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.WaitToUnlockPricingModel waitToUnlock = 6; */
        if (message.pricing.oneofKind === "waitToUnlock")
            WaitToUnlockPricingModel.internalBinaryWrite(message.pricing.waitToUnlock, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.VoucherPricingModel voucher = 7; */
        if (message.pricing.oneofKind === "voucher")
            VoucherPricingModel.internalBinaryWrite(message.pricing.voucher, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.PricingModelRotation rotations = 9; */
        for (let i = 0; i < message.rotations.length; i++)
            PricingModelRotation.internalBinaryWrite(message.rotations[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue currentRotationId = 10; */
        if (message.currentRotationId)
            StringValue.internalBinaryWrite(message.currentRotationId, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.PricingModel
 */
export const PricingModel = new PricingModel$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Pricing
 */
export const Pricing = new ServiceType("wuxiaworld.api.v2.Pricing", [
    { name: "GetActivePricing", options: {}, I: GetActivePricingRequest, O: GetActivePricingResponse },
    { name: "GetActivePricingRotations", options: {}, I: GetActivePricingRotationsRequest, O: GetActivePricingRotationsResponse }
]);
