// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/product_surveys.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
import { ProductType } from "./products";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetProductSurveyForTypeRequest
 */
export interface GetProductSurveyForTypeRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductType productType = 1
     */
    productType: ProductType;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetProductSurveyForTypeResponse
 */
export interface GetProductSurveyForTypeResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductSurveyItem item = 1
     */
    item?: ProductSurveyItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddProductSurveyRequest
 */
export interface AddProductSurveyRequest {
    /**
     * @generated from protobuf field: string surveyId = 1
     */
    surveyId: string;
    /**
     * @generated from protobuf field: int32 productId = 2
     */
    productId: number;
    /**
     * @generated from protobuf field: google.protobuf.StringValue data = 3
     */
    data?: StringValue;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo = 4
     */
    subscriptionInfo?: UserProductSurvey_SubscriptionInfo;
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer answers = 5
     */
    answers: AddProductSurveyRequest_AddSurveyAnswer[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer
 */
export interface AddProductSurveyRequest_AddSurveyAnswer {
    /**
     * @generated from protobuf field: string questionId = 1
     */
    questionId: string;
    /**
     * @generated from protobuf field: string data = 2
     */
    data: string;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.AddProductSurveyResponse
 */
export interface AddProductSurveyResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserProductSurvey userSurvey = 1
     */
    userSurvey?: UserProductSurvey;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserProductSurvey
 */
export interface UserProductSurvey {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string userId = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp createdAt = 3
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updatedAt = 4
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductSurveyItem survey = 6
     */
    survey?: ProductSurveyItem;
    /**
     * @generated from protobuf field: string answerData = 7
     */
    answerData: string;
    /**
     * @generated from protobuf field: int32 productId = 8
     */
    productId: number;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo = 9
     */
    subscriptionInfo?: UserProductSurvey_SubscriptionInfo;
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.ProductSurveyAnswer answers = 10
     */
    answers: ProductSurveyAnswer[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo
 */
export interface UserProductSurvey_SubscriptionInfo {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserProductSurvey.SurveySubscriptionType type = 2
     */
    type: UserProductSurvey_SurveySubscriptionType;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.UserProductSurvey.SurveySubscriptionType
 */
export enum UserProductSurvey_SurveySubscriptionType {
    /**
     * @generated from protobuf enum value: Vip = 0;
     */
    Vip = 0,
    /**
     * @generated from protobuf enum value: Sponsor = 1;
     */
    Sponsor = 1,
    /**
     * @generated from protobuf enum value: Unknown = -1;
     */
    Unknown = -1
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ProductSurveyQuestion
 */
export interface ProductSurveyQuestion {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string question = 2
     */
    question: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue description = 3
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: int32 order = 4
     */
    order: number;
    /**
     * @generated from protobuf field: string data = 5
     */
    data: string;
    /**
     * @generated from protobuf field: string surveyId = 6
     */
    surveyId: string;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductSurveyQuestionType type = 7
     */
    type: ProductSurveyQuestionType;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ProductSurveyAnswer
 */
export interface ProductSurveyAnswer {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string questionId = 2
     */
    questionId: string;
    /**
     * @generated from protobuf field: string data = 3
     */
    data: string;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.ProductSurveyItem
 */
export interface ProductSurveyItem {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue description = 3
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductType productType = 4
     */
    productType: ProductType;
    /**
     * @generated from protobuf field: bool isMultipleEntriesAllowed = 5
     */
    isMultipleEntriesAllowed: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp createdAt = 6
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updatedAt = 7
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.ProductSurveyQuestion questions = 8
     */
    questions: ProductSurveyQuestion[];
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.ProductSurveyQuestionType
 */
export enum ProductSurveyQuestionType {
    /**
     * @generated from protobuf enum value: Text = 0;
     */
    Text = 0,
    /**
     * @generated from protobuf enum value: Number = 1;
     */
    Number = 1,
    /**
     * @generated from protobuf enum value: MultipleChoice = 2;
     */
    MultipleChoice = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GetProductSurveyForTypeRequest$Type extends MessageType<GetProductSurveyForTypeRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetProductSurveyForTypeRequest", [
            { no: 1, name: "productType", kind: "enum", T: () => ["wuxiaworld.api.v2.ProductType", ProductType] }
        ]);
    }
    create(value?: PartialMessage<GetProductSurveyForTypeRequest>): GetProductSurveyForTypeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.productType = 0;
        if (value !== undefined)
            reflectionMergePartial<GetProductSurveyForTypeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProductSurveyForTypeRequest): GetProductSurveyForTypeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.ProductType productType */ 1:
                    message.productType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProductSurveyForTypeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.ProductType productType = 1; */
        if (message.productType !== 0)
            writer.tag(1, WireType.Varint).int32(message.productType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetProductSurveyForTypeRequest
 */
export const GetProductSurveyForTypeRequest = new GetProductSurveyForTypeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProductSurveyForTypeResponse$Type extends MessageType<GetProductSurveyForTypeResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetProductSurveyForTypeResponse", [
            { no: 1, name: "item", kind: "message", T: () => ProductSurveyItem }
        ]);
    }
    create(value?: PartialMessage<GetProductSurveyForTypeResponse>): GetProductSurveyForTypeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetProductSurveyForTypeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProductSurveyForTypeResponse): GetProductSurveyForTypeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.ProductSurveyItem item */ 1:
                    message.item = ProductSurveyItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProductSurveyForTypeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.ProductSurveyItem item = 1; */
        if (message.item)
            ProductSurveyItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetProductSurveyForTypeResponse
 */
export const GetProductSurveyForTypeResponse = new GetProductSurveyForTypeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddProductSurveyRequest$Type extends MessageType<AddProductSurveyRequest> {
    constructor() {
        super("wuxiaworld.api.v2.AddProductSurveyRequest", [
            { no: 1, name: "surveyId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "productId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "data", kind: "message", T: () => StringValue },
            { no: 4, name: "subscriptionInfo", kind: "message", T: () => UserProductSurvey_SubscriptionInfo },
            { no: 5, name: "answers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AddProductSurveyRequest_AddSurveyAnswer }
        ]);
    }
    create(value?: PartialMessage<AddProductSurveyRequest>): AddProductSurveyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.surveyId = "";
        message.productId = 0;
        message.answers = [];
        if (value !== undefined)
            reflectionMergePartial<AddProductSurveyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddProductSurveyRequest): AddProductSurveyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string surveyId */ 1:
                    message.surveyId = reader.string();
                    break;
                case /* int32 productId */ 2:
                    message.productId = reader.int32();
                    break;
                case /* google.protobuf.StringValue data */ 3:
                    message.data = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                case /* wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo */ 4:
                    message.subscriptionInfo = UserProductSurvey_SubscriptionInfo.internalBinaryRead(reader, reader.uint32(), options, message.subscriptionInfo);
                    break;
                case /* repeated wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer answers */ 5:
                    message.answers.push(AddProductSurveyRequest_AddSurveyAnswer.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddProductSurveyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string surveyId = 1; */
        if (message.surveyId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.surveyId);
        /* int32 productId = 2; */
        if (message.productId !== 0)
            writer.tag(2, WireType.Varint).int32(message.productId);
        /* google.protobuf.StringValue data = 3; */
        if (message.data)
            StringValue.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo = 4; */
        if (message.subscriptionInfo)
            UserProductSurvey_SubscriptionInfo.internalBinaryWrite(message.subscriptionInfo, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer answers = 5; */
        for (let i = 0; i < message.answers.length; i++)
            AddProductSurveyRequest_AddSurveyAnswer.internalBinaryWrite(message.answers[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddProductSurveyRequest
 */
export const AddProductSurveyRequest = new AddProductSurveyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddProductSurveyRequest_AddSurveyAnswer$Type extends MessageType<AddProductSurveyRequest_AddSurveyAnswer> {
    constructor() {
        super("wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer", [
            { no: 1, name: "questionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddProductSurveyRequest_AddSurveyAnswer>): AddProductSurveyRequest_AddSurveyAnswer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.questionId = "";
        message.data = "";
        if (value !== undefined)
            reflectionMergePartial<AddProductSurveyRequest_AddSurveyAnswer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddProductSurveyRequest_AddSurveyAnswer): AddProductSurveyRequest_AddSurveyAnswer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string questionId */ 1:
                    message.questionId = reader.string();
                    break;
                case /* string data */ 2:
                    message.data = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddProductSurveyRequest_AddSurveyAnswer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string questionId = 1; */
        if (message.questionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.questionId);
        /* string data = 2; */
        if (message.data !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.data);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddProductSurveyRequest.AddSurveyAnswer
 */
export const AddProductSurveyRequest_AddSurveyAnswer = new AddProductSurveyRequest_AddSurveyAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddProductSurveyResponse$Type extends MessageType<AddProductSurveyResponse> {
    constructor() {
        super("wuxiaworld.api.v2.AddProductSurveyResponse", [
            { no: 1, name: "userSurvey", kind: "message", T: () => UserProductSurvey }
        ]);
    }
    create(value?: PartialMessage<AddProductSurveyResponse>): AddProductSurveyResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AddProductSurveyResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddProductSurveyResponse): AddProductSurveyResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.UserProductSurvey userSurvey */ 1:
                    message.userSurvey = UserProductSurvey.internalBinaryRead(reader, reader.uint32(), options, message.userSurvey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddProductSurveyResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.UserProductSurvey userSurvey = 1; */
        if (message.userSurvey)
            UserProductSurvey.internalBinaryWrite(message.userSurvey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.AddProductSurveyResponse
 */
export const AddProductSurveyResponse = new AddProductSurveyResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserProductSurvey$Type extends MessageType<UserProductSurvey> {
    constructor() {
        super("wuxiaworld.api.v2.UserProductSurvey", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "createdAt", kind: "message", T: () => Timestamp },
            { no: 4, name: "updatedAt", kind: "message", T: () => Timestamp },
            { no: 6, name: "survey", kind: "message", T: () => ProductSurveyItem },
            { no: 7, name: "answerData", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "productId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "subscriptionInfo", kind: "message", T: () => UserProductSurvey_SubscriptionInfo },
            { no: 10, name: "answers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductSurveyAnswer }
        ]);
    }
    create(value?: PartialMessage<UserProductSurvey>): UserProductSurvey {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.answerData = "";
        message.productId = 0;
        message.answers = [];
        if (value !== undefined)
            reflectionMergePartial<UserProductSurvey>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserProductSurvey): UserProductSurvey {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string userId */ 2:
                    message.userId = reader.string();
                    break;
                case /* google.protobuf.Timestamp createdAt */ 3:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updatedAt */ 4:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* wuxiaworld.api.v2.ProductSurveyItem survey */ 6:
                    message.survey = ProductSurveyItem.internalBinaryRead(reader, reader.uint32(), options, message.survey);
                    break;
                case /* string answerData */ 7:
                    message.answerData = reader.string();
                    break;
                case /* int32 productId */ 8:
                    message.productId = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo */ 9:
                    message.subscriptionInfo = UserProductSurvey_SubscriptionInfo.internalBinaryRead(reader, reader.uint32(), options, message.subscriptionInfo);
                    break;
                case /* repeated wuxiaworld.api.v2.ProductSurveyAnswer answers */ 10:
                    message.answers.push(ProductSurveyAnswer.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserProductSurvey, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string userId = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* google.protobuf.Timestamp createdAt = 3; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updatedAt = 4; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.ProductSurveyItem survey = 6; */
        if (message.survey)
            ProductSurveyItem.internalBinaryWrite(message.survey, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string answerData = 7; */
        if (message.answerData !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.answerData);
        /* int32 productId = 8; */
        if (message.productId !== 0)
            writer.tag(8, WireType.Varint).int32(message.productId);
        /* wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo subscriptionInfo = 9; */
        if (message.subscriptionInfo)
            UserProductSurvey_SubscriptionInfo.internalBinaryWrite(message.subscriptionInfo, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.ProductSurveyAnswer answers = 10; */
        for (let i = 0; i < message.answers.length; i++)
            ProductSurveyAnswer.internalBinaryWrite(message.answers[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserProductSurvey
 */
export const UserProductSurvey = new UserProductSurvey$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserProductSurvey_SubscriptionInfo$Type extends MessageType<UserProductSurvey_SubscriptionInfo> {
    constructor() {
        super("wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.UserProductSurvey.SurveySubscriptionType", UserProductSurvey_SurveySubscriptionType] }
        ]);
    }
    create(value?: PartialMessage<UserProductSurvey_SubscriptionInfo>): UserProductSurvey_SubscriptionInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<UserProductSurvey_SubscriptionInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserProductSurvey_SubscriptionInfo): UserProductSurvey_SubscriptionInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* wuxiaworld.api.v2.UserProductSurvey.SurveySubscriptionType type */ 2:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserProductSurvey_SubscriptionInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* wuxiaworld.api.v2.UserProductSurvey.SurveySubscriptionType type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserProductSurvey.SubscriptionInfo
 */
export const UserProductSurvey_SubscriptionInfo = new UserProductSurvey_SubscriptionInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductSurveyQuestion$Type extends MessageType<ProductSurveyQuestion> {
    constructor() {
        super("wuxiaworld.api.v2.ProductSurveyQuestion", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "question", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "message", T: () => StringValue },
            { no: 4, name: "order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "surveyId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "type", kind: "enum", T: () => ["wuxiaworld.api.v2.ProductSurveyQuestionType", ProductSurveyQuestionType] }
        ]);
    }
    create(value?: PartialMessage<ProductSurveyQuestion>): ProductSurveyQuestion {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.question = "";
        message.order = 0;
        message.data = "";
        message.surveyId = "";
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<ProductSurveyQuestion>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductSurveyQuestion): ProductSurveyQuestion {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string question */ 2:
                    message.question = reader.string();
                    break;
                case /* google.protobuf.StringValue description */ 3:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* int32 order */ 4:
                    message.order = reader.int32();
                    break;
                case /* string data */ 5:
                    message.data = reader.string();
                    break;
                case /* string surveyId */ 6:
                    message.surveyId = reader.string();
                    break;
                case /* wuxiaworld.api.v2.ProductSurveyQuestionType type */ 7:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductSurveyQuestion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string question = 2; */
        if (message.question !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.question);
        /* google.protobuf.StringValue description = 3; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* int32 order = 4; */
        if (message.order !== 0)
            writer.tag(4, WireType.Varint).int32(message.order);
        /* string data = 5; */
        if (message.data !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.data);
        /* string surveyId = 6; */
        if (message.surveyId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.surveyId);
        /* wuxiaworld.api.v2.ProductSurveyQuestionType type = 7; */
        if (message.type !== 0)
            writer.tag(7, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ProductSurveyQuestion
 */
export const ProductSurveyQuestion = new ProductSurveyQuestion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductSurveyAnswer$Type extends MessageType<ProductSurveyAnswer> {
    constructor() {
        super("wuxiaworld.api.v2.ProductSurveyAnswer", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "questionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ProductSurveyAnswer>): ProductSurveyAnswer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.questionId = "";
        message.data = "";
        if (value !== undefined)
            reflectionMergePartial<ProductSurveyAnswer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductSurveyAnswer): ProductSurveyAnswer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string questionId */ 2:
                    message.questionId = reader.string();
                    break;
                case /* string data */ 3:
                    message.data = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductSurveyAnswer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string questionId = 2; */
        if (message.questionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.questionId);
        /* string data = 3; */
        if (message.data !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.data);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ProductSurveyAnswer
 */
export const ProductSurveyAnswer = new ProductSurveyAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductSurveyItem$Type extends MessageType<ProductSurveyItem> {
    constructor() {
        super("wuxiaworld.api.v2.ProductSurveyItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "message", T: () => StringValue },
            { no: 4, name: "productType", kind: "enum", T: () => ["wuxiaworld.api.v2.ProductType", ProductType] },
            { no: 5, name: "isMultipleEntriesAllowed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "createdAt", kind: "message", T: () => Timestamp },
            { no: 7, name: "updatedAt", kind: "message", T: () => Timestamp },
            { no: 8, name: "questions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductSurveyQuestion }
        ]);
    }
    create(value?: PartialMessage<ProductSurveyItem>): ProductSurveyItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.productType = 0;
        message.isMultipleEntriesAllowed = false;
        message.questions = [];
        if (value !== undefined)
            reflectionMergePartial<ProductSurveyItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductSurveyItem): ProductSurveyItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* google.protobuf.StringValue description */ 3:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* wuxiaworld.api.v2.ProductType productType */ 4:
                    message.productType = reader.int32();
                    break;
                case /* bool isMultipleEntriesAllowed */ 5:
                    message.isMultipleEntriesAllowed = reader.bool();
                    break;
                case /* google.protobuf.Timestamp createdAt */ 6:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updatedAt */ 7:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* repeated wuxiaworld.api.v2.ProductSurveyQuestion questions */ 8:
                    message.questions.push(ProductSurveyQuestion.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductSurveyItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* google.protobuf.StringValue description = 3; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.ProductType productType = 4; */
        if (message.productType !== 0)
            writer.tag(4, WireType.Varint).int32(message.productType);
        /* bool isMultipleEntriesAllowed = 5; */
        if (message.isMultipleEntriesAllowed !== false)
            writer.tag(5, WireType.Varint).bool(message.isMultipleEntriesAllowed);
        /* google.protobuf.Timestamp createdAt = 6; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updatedAt = 7; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.ProductSurveyQuestion questions = 8; */
        for (let i = 0; i < message.questions.length; i++)
            ProductSurveyQuestion.internalBinaryWrite(message.questions[i], writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.ProductSurveyItem
 */
export const ProductSurveyItem = new ProductSurveyItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.ProductSurveys
 */
export const ProductSurveys = new ServiceType("wuxiaworld.api.v2.ProductSurveys", [
    { name: "GetProductSurveyForType", options: {}, I: GetProductSurveyForTypeRequest, O: GetProductSurveyForTypeResponse },
    { name: "AddProductSurvey", options: {}, I: AddProductSurveyRequest, O: AddProductSurveyResponse }
]);
