// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/sponsors.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ProductItem } from "./products";
import { Int32Value } from "../google/protobuf/wrappers";
import { StringValue } from "../google/protobuf/wrappers";
import { DecimalValue } from "./types";
import { Discount } from "./discounts";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetSponsorPlansRequest
 */
export interface GetSponsorPlansRequest {
    /**
     * @generated from protobuf field: int32 novelId = 1
     */
    novelId: number;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetSponsorPlansRequest.SortType sortType = 2
     */
    sortType: GetSponsorPlansRequest_SortType;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection sortDirection = 3
     */
    sortDirection: GetSponsorPlansRequest_SortDirection;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetSponsorPlansRequest.SortType
 */
export enum GetSponsorPlansRequest_SortType {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: Name = 1;
     */
    Name = 1,
    /**
     * @generated from protobuf enum value: Popular = 2;
     */
    Popular = 2,
    /**
     * @generated from protobuf enum value: AdvanceChapters = 3;
     */
    AdvanceChapters = 3
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection
 */
export enum GetSponsorPlansRequest_SortDirection {
    /**
     * @generated from protobuf enum value: ASC = 0;
     */
    ASC = 0,
    /**
     * @generated from protobuf enum value: DESC = 1;
     */
    DESC = 1
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetSponsorPlansResponse
 */
export interface GetSponsorPlansResponse {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.SponsorPlanItem items = 1
     */
    items: SponsorPlanItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SponsorPlanDiscountInfo
 */
export interface SponsorPlanDiscountInfo {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.Discount discounts = 1
     */
    discounts: Discount[];
    /**
     * @generated from protobuf field: customTypes.DecimalValue discountedPrice = 2
     */
    discountedPrice?: DecimalValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SponsorPlanItem
 */
export interface SponsorPlanItem {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue description = 3
     */
    description?: StringValue;
    /**
     * @generated from protobuf field: bool enabled = 4
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: bool visible = 5
     */
    visible: boolean;
    /**
     * @generated from protobuf field: int32 advanceChapterCount = 6
     */
    advanceChapterCount: number;
    /**
     * @generated from protobuf field: string planId = 7
     */
    planId: string;
    /**
     * @generated from protobuf field: customTypes.DecimalValue price = 8
     */
    price?: DecimalValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value karmaPrice = 9
     */
    karmaPrice?: Int32Value;
    /**
     * @generated from protobuf field: bool paused = 10
     */
    paused: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.SponsorPlanItem.NovelInfo novelInfo = 11
     */
    novelInfo?: SponsorPlanItem_NovelInfo;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ProductItem product = 12
     */
    product?: ProductItem;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.SponsorPlanDiscountInfo discountInfo = 13
     */
    discountInfo?: SponsorPlanDiscountInfo;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SponsorPlanItem.NovelInfo
 */
export interface SponsorPlanItem_NovelInfo {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string slug = 3
     */
    slug: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverUrl = 4
     */
    coverUrl?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue coverBlurHash = 5
     */
    coverBlurHash?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue sponsorDescription = 6
     */
    sponsorDescription?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetSponsorPlansRequest$Type extends MessageType<GetSponsorPlansRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetSponsorPlansRequest", [
            { no: 1, name: "novelId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "sortType", kind: "enum", T: () => ["wuxiaworld.api.v2.GetSponsorPlansRequest.SortType", GetSponsorPlansRequest_SortType] },
            { no: 3, name: "sortDirection", kind: "enum", T: () => ["wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection", GetSponsorPlansRequest_SortDirection] }
        ]);
    }
    create(value?: PartialMessage<GetSponsorPlansRequest>): GetSponsorPlansRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.novelId = 0;
        message.sortType = 0;
        message.sortDirection = 0;
        if (value !== undefined)
            reflectionMergePartial<GetSponsorPlansRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSponsorPlansRequest): GetSponsorPlansRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 novelId */ 1:
                    message.novelId = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.GetSponsorPlansRequest.SortType sortType */ 2:
                    message.sortType = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection sortDirection */ 3:
                    message.sortDirection = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSponsorPlansRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 novelId = 1; */
        if (message.novelId !== 0)
            writer.tag(1, WireType.Varint).int32(message.novelId);
        /* wuxiaworld.api.v2.GetSponsorPlansRequest.SortType sortType = 2; */
        if (message.sortType !== 0)
            writer.tag(2, WireType.Varint).int32(message.sortType);
        /* wuxiaworld.api.v2.GetSponsorPlansRequest.SortDirection sortDirection = 3; */
        if (message.sortDirection !== 0)
            writer.tag(3, WireType.Varint).int32(message.sortDirection);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetSponsorPlansRequest
 */
export const GetSponsorPlansRequest = new GetSponsorPlansRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSponsorPlansResponse$Type extends MessageType<GetSponsorPlansResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetSponsorPlansResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SponsorPlanItem }
        ]);
    }
    create(value?: PartialMessage<GetSponsorPlansResponse>): GetSponsorPlansResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetSponsorPlansResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSponsorPlansResponse): GetSponsorPlansResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.SponsorPlanItem items */ 1:
                    message.items.push(SponsorPlanItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSponsorPlansResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.SponsorPlanItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            SponsorPlanItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetSponsorPlansResponse
 */
export const GetSponsorPlansResponse = new GetSponsorPlansResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SponsorPlanDiscountInfo$Type extends MessageType<SponsorPlanDiscountInfo> {
    constructor() {
        super("wuxiaworld.api.v2.SponsorPlanDiscountInfo", [
            { no: 1, name: "discounts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Discount },
            { no: 2, name: "discountedPrice", kind: "message", T: () => DecimalValue }
        ]);
    }
    create(value?: PartialMessage<SponsorPlanDiscountInfo>): SponsorPlanDiscountInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.discounts = [];
        if (value !== undefined)
            reflectionMergePartial<SponsorPlanDiscountInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SponsorPlanDiscountInfo): SponsorPlanDiscountInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.Discount discounts */ 1:
                    message.discounts.push(Discount.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* customTypes.DecimalValue discountedPrice */ 2:
                    message.discountedPrice = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.discountedPrice);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SponsorPlanDiscountInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.Discount discounts = 1; */
        for (let i = 0; i < message.discounts.length; i++)
            Discount.internalBinaryWrite(message.discounts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* customTypes.DecimalValue discountedPrice = 2; */
        if (message.discountedPrice)
            DecimalValue.internalBinaryWrite(message.discountedPrice, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SponsorPlanDiscountInfo
 */
export const SponsorPlanDiscountInfo = new SponsorPlanDiscountInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SponsorPlanItem$Type extends MessageType<SponsorPlanItem> {
    constructor() {
        super("wuxiaworld.api.v2.SponsorPlanItem", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "message", T: () => StringValue },
            { no: 4, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "visible", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "advanceChapterCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "planId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "price", kind: "message", T: () => DecimalValue },
            { no: 9, name: "karmaPrice", kind: "message", T: () => Int32Value },
            { no: 10, name: "paused", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "novelInfo", kind: "message", T: () => SponsorPlanItem_NovelInfo },
            { no: 12, name: "product", kind: "message", T: () => ProductItem },
            { no: 13, name: "discountInfo", kind: "message", T: () => SponsorPlanDiscountInfo }
        ]);
    }
    create(value?: PartialMessage<SponsorPlanItem>): SponsorPlanItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.enabled = false;
        message.visible = false;
        message.advanceChapterCount = 0;
        message.planId = "";
        message.paused = false;
        if (value !== undefined)
            reflectionMergePartial<SponsorPlanItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SponsorPlanItem): SponsorPlanItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* google.protobuf.StringValue description */ 3:
                    message.description = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.description);
                    break;
                case /* bool enabled */ 4:
                    message.enabled = reader.bool();
                    break;
                case /* bool visible */ 5:
                    message.visible = reader.bool();
                    break;
                case /* int32 advanceChapterCount */ 6:
                    message.advanceChapterCount = reader.int32();
                    break;
                case /* string planId */ 7:
                    message.planId = reader.string();
                    break;
                case /* customTypes.DecimalValue price */ 8:
                    message.price = DecimalValue.internalBinaryRead(reader, reader.uint32(), options, message.price);
                    break;
                case /* google.protobuf.Int32Value karmaPrice */ 9:
                    message.karmaPrice = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.karmaPrice);
                    break;
                case /* bool paused */ 10:
                    message.paused = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.SponsorPlanItem.NovelInfo novelInfo */ 11:
                    message.novelInfo = SponsorPlanItem_NovelInfo.internalBinaryRead(reader, reader.uint32(), options, message.novelInfo);
                    break;
                case /* wuxiaworld.api.v2.ProductItem product */ 12:
                    message.product = ProductItem.internalBinaryRead(reader, reader.uint32(), options, message.product);
                    break;
                case /* wuxiaworld.api.v2.SponsorPlanDiscountInfo discountInfo */ 13:
                    message.discountInfo = SponsorPlanDiscountInfo.internalBinaryRead(reader, reader.uint32(), options, message.discountInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SponsorPlanItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* google.protobuf.StringValue description = 3; */
        if (message.description)
            StringValue.internalBinaryWrite(message.description, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool enabled = 4; */
        if (message.enabled !== false)
            writer.tag(4, WireType.Varint).bool(message.enabled);
        /* bool visible = 5; */
        if (message.visible !== false)
            writer.tag(5, WireType.Varint).bool(message.visible);
        /* int32 advanceChapterCount = 6; */
        if (message.advanceChapterCount !== 0)
            writer.tag(6, WireType.Varint).int32(message.advanceChapterCount);
        /* string planId = 7; */
        if (message.planId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.planId);
        /* customTypes.DecimalValue price = 8; */
        if (message.price)
            DecimalValue.internalBinaryWrite(message.price, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value karmaPrice = 9; */
        if (message.karmaPrice)
            Int32Value.internalBinaryWrite(message.karmaPrice, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* bool paused = 10; */
        if (message.paused !== false)
            writer.tag(10, WireType.Varint).bool(message.paused);
        /* wuxiaworld.api.v2.SponsorPlanItem.NovelInfo novelInfo = 11; */
        if (message.novelInfo)
            SponsorPlanItem_NovelInfo.internalBinaryWrite(message.novelInfo, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.ProductItem product = 12; */
        if (message.product)
            ProductItem.internalBinaryWrite(message.product, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.SponsorPlanDiscountInfo discountInfo = 13; */
        if (message.discountInfo)
            SponsorPlanDiscountInfo.internalBinaryWrite(message.discountInfo, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SponsorPlanItem
 */
export const SponsorPlanItem = new SponsorPlanItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SponsorPlanItem_NovelInfo$Type extends MessageType<SponsorPlanItem_NovelInfo> {
    constructor() {
        super("wuxiaworld.api.v2.SponsorPlanItem.NovelInfo", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "coverUrl", kind: "message", T: () => StringValue },
            { no: 5, name: "coverBlurHash", kind: "message", T: () => StringValue },
            { no: 6, name: "sponsorDescription", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<SponsorPlanItem_NovelInfo>): SponsorPlanItem_NovelInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.slug = "";
        if (value !== undefined)
            reflectionMergePartial<SponsorPlanItem_NovelInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SponsorPlanItem_NovelInfo): SponsorPlanItem_NovelInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string slug */ 3:
                    message.slug = reader.string();
                    break;
                case /* google.protobuf.StringValue coverUrl */ 4:
                    message.coverUrl = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.coverUrl);
                    break;
                case /* google.protobuf.StringValue coverBlurHash */ 5:
                    message.coverBlurHash = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.coverBlurHash);
                    break;
                case /* google.protobuf.StringValue sponsorDescription */ 6:
                    message.sponsorDescription = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.sponsorDescription);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SponsorPlanItem_NovelInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string slug = 3; */
        if (message.slug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.slug);
        /* google.protobuf.StringValue coverUrl = 4; */
        if (message.coverUrl)
            StringValue.internalBinaryWrite(message.coverUrl, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue coverBlurHash = 5; */
        if (message.coverBlurHash)
            StringValue.internalBinaryWrite(message.coverBlurHash, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue sponsorDescription = 6; */
        if (message.sponsorDescription)
            StringValue.internalBinaryWrite(message.sponsorDescription, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SponsorPlanItem.NovelInfo
 */
export const SponsorPlanItem_NovelInfo = new SponsorPlanItem_NovelInfo$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Sponsors
 */
export const Sponsors = new ServiceType("wuxiaworld.api.v2.Sponsors", [
    { name: "GetSponsorPlans", options: {}, I: GetSponsorPlansRequest, O: GetSponsorPlansResponse }
]);
