// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/types.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Example: 12345.6789 -> { units = 12345, nanos = 678900000 }
 *
 * @generated from protobuf message wuxiaworld.api.v2.DecimalValue
 */
export interface DecimalValue {
    /**
     * Whole units part of the amount
     *
     * @generated from protobuf field: int64 units = 1
     */
    units: number;
    /**
     * Nano units of the amount (10^-9)
     * Must be same sign as units
     *
     * @generated from protobuf field: sfixed32 nanos = 2
     */
    nanos: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.Date
 */
export interface Date {
    /**
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     *
     * @generated from protobuf field: int32 year = 1
     */
    year: number;
    /**
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     *
     * @generated from protobuf field: int32 month = 2
     */
    month: number;
    /**
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     *
     * @generated from protobuf field: int32 day = 3
     */
    day: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class DecimalValue$Type extends MessageType<DecimalValue> {
    constructor() {
        super("wuxiaworld.api.v2.DecimalValue", [
            { no: 1, name: "units", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "nanos", kind: "scalar", T: 15 /*ScalarType.SFIXED32*/ }
        ]);
    }
    create(value?: PartialMessage<DecimalValue>): DecimalValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.units = 0;
        message.nanos = 0;
        if (value !== undefined)
            reflectionMergePartial<DecimalValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DecimalValue): DecimalValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 units */ 1:
                    message.units = reader.int64().toNumber();
                    break;
                case /* sfixed32 nanos */ 2:
                    message.nanos = reader.sfixed32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DecimalValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 units = 1; */
        if (message.units !== 0)
            writer.tag(1, WireType.Varint).int64(message.units);
        /* sfixed32 nanos = 2; */
        if (message.nanos !== 0)
            writer.tag(2, WireType.Bit32).sfixed32(message.nanos);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.DecimalValue
 */
export const DecimalValue = new DecimalValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Date$Type extends MessageType<Date> {
    constructor() {
        super("wuxiaworld.api.v2.Date", [
            { no: 1, name: "year", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "month", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "day", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Date>): Date {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.year = 0;
        message.month = 0;
        message.day = 0;
        if (value !== undefined)
            reflectionMergePartial<Date>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Date): Date {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 year */ 1:
                    message.year = reader.int32();
                    break;
                case /* int32 month */ 2:
                    message.month = reader.int32();
                    break;
                case /* int32 day */ 3:
                    message.day = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Date, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 year = 1; */
        if (message.year !== 0)
            writer.tag(1, WireType.Varint).int32(message.year);
        /* int32 month = 2; */
        if (message.month !== 0)
            writer.tag(2, WireType.Varint).int32(message.month);
        /* int32 day = 3; */
        if (message.day !== 0)
            writer.tag(3, WireType.Varint).int32(message.day);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.Date
 */
export const Date = new Date$Type();
