// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/updates.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ChapterItem } from "./chapters";
import { NovelItem } from "./novels";
import { PageInfoResponse } from "./pagination";
import { Timestamp } from "../google/protobuf/timestamp";
import { PageInfoRequest } from "./pagination";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetLatestUpdatesRequest
 */
export interface GetLatestUpdatesRequest {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoRequest pageInfo = 1
     */
    pageInfo?: PageInfoRequest;
    /**
     * @generated from protobuf field: bool isOnlyActiveNovels = 2
     */
    isOnlyActiveNovels: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetLatestUpdatesRequest.SortBy sortBy = 3
     */
    sortBy: GetLatestUpdatesRequest_SortBy;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.GetLatestUpdatesRequest.SortDir sortDir = 4
     */
    sortDir: GetLatestUpdatesRequest_SortDir;
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetLatestUpdatesRequest.SortBy
 */
export enum GetLatestUpdatesRequest_SortBy {
    /**
     * @generated from protobuf enum value: Name = 0;
     */
    Name = 0,
    /**
     * @generated from protobuf enum value: LastUpdated = 1;
     */
    LastUpdated = 1
}
/**
 * @generated from protobuf enum wuxiaworld.api.v2.GetLatestUpdatesRequest.SortDir
 */
export enum GetLatestUpdatesRequest_SortDir {
    /**
     * @generated from protobuf enum value: Asc = 0;
     */
    Asc = 0,
    /**
     * @generated from protobuf enum value: Desc = 1;
     */
    Desc = 1
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetLatestUpdatesResponse
 */
export interface GetLatestUpdatesResponse {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp lastUpdated = 1
     */
    lastUpdated?: Timestamp;
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.UpdatesItem latestUpdates = 2
     */
    latestUpdates: UpdatesItem[];
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.PageInfoResponse pageInfo = 3
     */
    pageInfo?: PageInfoResponse;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UpdatesItem
 */
export interface UpdatesItem {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.NovelItem novel = 1
     */
    novel?: NovelItem;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.ChapterItem chapter = 2
     */
    chapter?: ChapterItem;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetLatestUpdatesRequest$Type extends MessageType<GetLatestUpdatesRequest> {
    constructor() {
        super("wuxiaworld.api.v2.GetLatestUpdatesRequest", [
            { no: 1, name: "pageInfo", kind: "message", T: () => PageInfoRequest, options: { "wuxiaworld.api.v2.required": { value: true } } },
            { no: 2, name: "isOnlyActiveNovels", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "sortBy", kind: "enum", T: () => ["wuxiaworld.api.v2.GetLatestUpdatesRequest.SortBy", GetLatestUpdatesRequest_SortBy] },
            { no: 4, name: "sortDir", kind: "enum", T: () => ["wuxiaworld.api.v2.GetLatestUpdatesRequest.SortDir", GetLatestUpdatesRequest_SortDir] }
        ]);
    }
    create(value?: PartialMessage<GetLatestUpdatesRequest>): GetLatestUpdatesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isOnlyActiveNovels = false;
        message.sortBy = 0;
        message.sortDir = 0;
        if (value !== undefined)
            reflectionMergePartial<GetLatestUpdatesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLatestUpdatesRequest): GetLatestUpdatesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.PageInfoRequest pageInfo */ 1:
                    message.pageInfo = PageInfoRequest.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                case /* bool isOnlyActiveNovels */ 2:
                    message.isOnlyActiveNovels = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.GetLatestUpdatesRequest.SortBy sortBy */ 3:
                    message.sortBy = reader.int32();
                    break;
                case /* wuxiaworld.api.v2.GetLatestUpdatesRequest.SortDir sortDir */ 4:
                    message.sortDir = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLatestUpdatesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.PageInfoRequest pageInfo = 1; */
        if (message.pageInfo)
            PageInfoRequest.internalBinaryWrite(message.pageInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool isOnlyActiveNovels = 2; */
        if (message.isOnlyActiveNovels !== false)
            writer.tag(2, WireType.Varint).bool(message.isOnlyActiveNovels);
        /* wuxiaworld.api.v2.GetLatestUpdatesRequest.SortBy sortBy = 3; */
        if (message.sortBy !== 0)
            writer.tag(3, WireType.Varint).int32(message.sortBy);
        /* wuxiaworld.api.v2.GetLatestUpdatesRequest.SortDir sortDir = 4; */
        if (message.sortDir !== 0)
            writer.tag(4, WireType.Varint).int32(message.sortDir);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetLatestUpdatesRequest
 */
export const GetLatestUpdatesRequest = new GetLatestUpdatesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLatestUpdatesResponse$Type extends MessageType<GetLatestUpdatesResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetLatestUpdatesResponse", [
            { no: 1, name: "lastUpdated", kind: "message", T: () => Timestamp },
            { no: 2, name: "latestUpdates", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => UpdatesItem },
            { no: 3, name: "pageInfo", kind: "message", T: () => PageInfoResponse }
        ]);
    }
    create(value?: PartialMessage<GetLatestUpdatesResponse>): GetLatestUpdatesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.latestUpdates = [];
        if (value !== undefined)
            reflectionMergePartial<GetLatestUpdatesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLatestUpdatesResponse): GetLatestUpdatesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp lastUpdated */ 1:
                    message.lastUpdated = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.lastUpdated);
                    break;
                case /* repeated wuxiaworld.api.v2.UpdatesItem latestUpdates */ 2:
                    message.latestUpdates.push(UpdatesItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* wuxiaworld.api.v2.PageInfoResponse pageInfo */ 3:
                    message.pageInfo = PageInfoResponse.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLatestUpdatesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp lastUpdated = 1; */
        if (message.lastUpdated)
            Timestamp.internalBinaryWrite(message.lastUpdated, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.UpdatesItem latestUpdates = 2; */
        for (let i = 0; i < message.latestUpdates.length; i++)
            UpdatesItem.internalBinaryWrite(message.latestUpdates[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.PageInfoResponse pageInfo = 3; */
        if (message.pageInfo)
            PageInfoResponse.internalBinaryWrite(message.pageInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetLatestUpdatesResponse
 */
export const GetLatestUpdatesResponse = new GetLatestUpdatesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatesItem$Type extends MessageType<UpdatesItem> {
    constructor() {
        super("wuxiaworld.api.v2.UpdatesItem", [
            { no: 1, name: "novel", kind: "message", T: () => NovelItem },
            { no: 2, name: "chapter", kind: "message", T: () => ChapterItem }
        ]);
    }
    create(value?: PartialMessage<UpdatesItem>): UpdatesItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdatesItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatesItem): UpdatesItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.NovelItem novel */ 1:
                    message.novel = NovelItem.internalBinaryRead(reader, reader.uint32(), options, message.novel);
                    break;
                case /* wuxiaworld.api.v2.ChapterItem chapter */ 2:
                    message.chapter = ChapterItem.internalBinaryRead(reader, reader.uint32(), options, message.chapter);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatesItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.NovelItem novel = 1; */
        if (message.novel)
            NovelItem.internalBinaryWrite(message.novel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.ChapterItem chapter = 2; */
        if (message.chapter)
            ChapterItem.internalBinaryWrite(message.chapter, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UpdatesItem
 */
export const UpdatesItem = new UpdatesItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Updates
 */
export const Updates = new ServiceType("wuxiaworld.api.v2.Updates", [
    { name: "GetLatestUpdates", options: {}, I: GetLatestUpdatesRequest, O: GetLatestUpdatesResponse }
]);
