// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/users.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { VipItem } from "./vips";
import { Timestamp } from "../google/protobuf/timestamp";
import { StringValue } from "../google/protobuf/wrappers";
import { UnlockedVipNovelInfo } from "./vips";
import { ObjectItem } from "./objects";
import { Role } from "./roles";
import { BoolValue } from "../google/protobuf/wrappers";
/**
 * @generated from protobuf message wuxiaworld.api.v2.GetMyUserResponse
 */
export interface GetMyUserResponse {
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserItem item = 1
     */
    item?: UserItem;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SetAvatarRequest
 */
export interface SetAvatarRequest {
    /**
     * @generated from protobuf field: bytes image = 1
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.SetAvatarChunkedRequest
 */
export interface SetAvatarChunkedRequest {
    /**
     * @generated from protobuf field: bytes chunk = 2
     */
    chunk: Uint8Array;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.DeleteAccountRequest
 */
export interface DeleteAccountRequest {
    /**
     * @generated from protobuf field: bool confirm = 1
     */
    confirm: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.DeleteAccountResponse
 */
export interface DeleteAccountResponse {
    /**
     * @generated from protobuf field: bool result = 1
     */
    result: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UpdateUserSettingsRequest
 */
export interface UpdateUserSettingsRequest {
    /**
     * @generated from protobuf field: google.protobuf.BoolValue autoUnlockChapters = 1
     */
    autoUnlockChapters?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue allowMarketing = 2
     */
    allowMarketing?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue isParagraphCommentsEnabled = 3
     */
    isParagraphCommentsEnabled?: BoolValue;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserSettings
 */
export interface UserSettings {
    /**
     * @generated from protobuf field: bool autoUnlockChapters = 1
     */
    autoUnlockChapters: boolean;
    /**
     * @generated from protobuf field: bool is2faEnabled = 2
     */
    is2FaEnabled: boolean;
    /**
     * @generated from protobuf field: bool allowMarketing = 3
     */
    allowMarketing: boolean;
    /**
     * @generated from protobuf field: bool isParagraphCommentsEnabled = 4
     */
    isParagraphCommentsEnabled: boolean;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserPermissions
 */
export interface UserPermissions {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.Role roles = 1
     */
    roles: Role[];
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.ObjectItem objects = 2
     */
    objects: ObjectItem[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserSponsorInfo
 */
export interface UserSponsorInfo {
    /**
     * @generated from protobuf field: int32 totalCount = 1
     */
    totalCount: number;
    /**
     * @generated from protobuf field: int32 activeCount = 2
     */
    activeCount: number;
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserVipInfo
 */
export interface UserVipInfo {
    /**
     * @generated from protobuf field: repeated wuxiaworld.api.v2.UnlockedVipNovelInfo unlockedNovels = 1
     */
    unlockedNovels: UnlockedVipNovelInfo[];
}
/**
 * @generated from protobuf message wuxiaworld.api.v2.UserItem
 */
export interface UserItem {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string userName = 2
     */
    userName: string;
    /**
     * @generated from protobuf field: google.protobuf.StringValue avatarUrl = 3
     */
    avatarUrl?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue email = 4
     */
    email?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp joinDate = 5
     */
    joinDate?: Timestamp;
    /**
     * @generated from protobuf field: bool isVipActive = 6
     */
    isVipActive: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.VipItem vip = 7
     */
    vip?: VipItem;
    /**
     * @generated from protobuf field: google.protobuf.StringValue flair = 8
     */
    flair?: StringValue;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserSettings settings = 9
     */
    settings?: UserSettings;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserPermissions permissions = 10
     */
    permissions?: UserPermissions;
    /**
     * @generated from protobuf field: bool isLegacy = 11
     */
    isLegacy: boolean;
    /**
     * @generated from protobuf field: bool isLegacyVip = 12
     */
    isLegacyVip: boolean;
    /**
     * @generated from protobuf field: bool isEmailVerified = 13
     */
    isEmailVerified: boolean;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserSponsorInfo sponsorInfo = 14
     */
    sponsorInfo?: UserSponsorInfo;
    /**
     * @generated from protobuf field: wuxiaworld.api.v2.UserVipInfo vipInfo = 15
     */
    vipInfo?: UserVipInfo;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetMyUserResponse$Type extends MessageType<GetMyUserResponse> {
    constructor() {
        super("wuxiaworld.api.v2.GetMyUserResponse", [
            { no: 1, name: "item", kind: "message", T: () => UserItem }
        ]);
    }
    create(value?: PartialMessage<GetMyUserResponse>): GetMyUserResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetMyUserResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyUserResponse): GetMyUserResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wuxiaworld.api.v2.UserItem item */ 1:
                    message.item = UserItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyUserResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wuxiaworld.api.v2.UserItem item = 1; */
        if (message.item)
            UserItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.GetMyUserResponse
 */
export const GetMyUserResponse = new GetMyUserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetAvatarRequest$Type extends MessageType<SetAvatarRequest> {
    constructor() {
        super("wuxiaworld.api.v2.SetAvatarRequest", [
            { no: 1, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SetAvatarRequest>): SetAvatarRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.image = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SetAvatarRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetAvatarRequest): SetAvatarRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes image */ 1:
                    message.image = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetAvatarRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes image = 1; */
        if (message.image.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.image);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SetAvatarRequest
 */
export const SetAvatarRequest = new SetAvatarRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetAvatarChunkedRequest$Type extends MessageType<SetAvatarChunkedRequest> {
    constructor() {
        super("wuxiaworld.api.v2.SetAvatarChunkedRequest", [
            { no: 2, name: "chunk", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SetAvatarChunkedRequest>): SetAvatarChunkedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chunk = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SetAvatarChunkedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetAvatarChunkedRequest): SetAvatarChunkedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes chunk */ 2:
                    message.chunk = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetAvatarChunkedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes chunk = 2; */
        if (message.chunk.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.chunk);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.SetAvatarChunkedRequest
 */
export const SetAvatarChunkedRequest = new SetAvatarChunkedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAccountRequest$Type extends MessageType<DeleteAccountRequest> {
    constructor() {
        super("wuxiaworld.api.v2.DeleteAccountRequest", [
            { no: 1, name: "confirm", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteAccountRequest>): DeleteAccountRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.confirm = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteAccountRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteAccountRequest): DeleteAccountRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool confirm */ 1:
                    message.confirm = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteAccountRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool confirm = 1; */
        if (message.confirm !== false)
            writer.tag(1, WireType.Varint).bool(message.confirm);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.DeleteAccountRequest
 */
export const DeleteAccountRequest = new DeleteAccountRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAccountResponse$Type extends MessageType<DeleteAccountResponse> {
    constructor() {
        super("wuxiaworld.api.v2.DeleteAccountResponse", [
            { no: 1, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteAccountResponse>): DeleteAccountResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.result = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteAccountResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteAccountResponse): DeleteAccountResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool result */ 1:
                    message.result = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteAccountResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool result = 1; */
        if (message.result !== false)
            writer.tag(1, WireType.Varint).bool(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.DeleteAccountResponse
 */
export const DeleteAccountResponse = new DeleteAccountResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserSettingsRequest$Type extends MessageType<UpdateUserSettingsRequest> {
    constructor() {
        super("wuxiaworld.api.v2.UpdateUserSettingsRequest", [
            { no: 1, name: "autoUnlockChapters", kind: "message", T: () => BoolValue },
            { no: 2, name: "allowMarketing", kind: "message", T: () => BoolValue },
            { no: 3, name: "isParagraphCommentsEnabled", kind: "message", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<UpdateUserSettingsRequest>): UpdateUserSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateUserSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserSettingsRequest): UpdateUserSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.BoolValue autoUnlockChapters */ 1:
                    message.autoUnlockChapters = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.autoUnlockChapters);
                    break;
                case /* google.protobuf.BoolValue allowMarketing */ 2:
                    message.allowMarketing = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.allowMarketing);
                    break;
                case /* google.protobuf.BoolValue isParagraphCommentsEnabled */ 3:
                    message.isParagraphCommentsEnabled = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.isParagraphCommentsEnabled);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.BoolValue autoUnlockChapters = 1; */
        if (message.autoUnlockChapters)
            BoolValue.internalBinaryWrite(message.autoUnlockChapters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue allowMarketing = 2; */
        if (message.allowMarketing)
            BoolValue.internalBinaryWrite(message.allowMarketing, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue isParagraphCommentsEnabled = 3; */
        if (message.isParagraphCommentsEnabled)
            BoolValue.internalBinaryWrite(message.isParagraphCommentsEnabled, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UpdateUserSettingsRequest
 */
export const UpdateUserSettingsRequest = new UpdateUserSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserSettings$Type extends MessageType<UserSettings> {
    constructor() {
        super("wuxiaworld.api.v2.UserSettings", [
            { no: 1, name: "autoUnlockChapters", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "is2faEnabled", kind: "scalar", jsonName: "is2faEnabled", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "allowMarketing", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "isParagraphCommentsEnabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UserSettings>): UserSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.autoUnlockChapters = false;
        message.is2FaEnabled = false;
        message.allowMarketing = false;
        message.isParagraphCommentsEnabled = false;
        if (value !== undefined)
            reflectionMergePartial<UserSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserSettings): UserSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool autoUnlockChapters */ 1:
                    message.autoUnlockChapters = reader.bool();
                    break;
                case /* bool is2faEnabled */ 2:
                    message.is2FaEnabled = reader.bool();
                    break;
                case /* bool allowMarketing */ 3:
                    message.allowMarketing = reader.bool();
                    break;
                case /* bool isParagraphCommentsEnabled */ 4:
                    message.isParagraphCommentsEnabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool autoUnlockChapters = 1; */
        if (message.autoUnlockChapters !== false)
            writer.tag(1, WireType.Varint).bool(message.autoUnlockChapters);
        /* bool is2faEnabled = 2; */
        if (message.is2FaEnabled !== false)
            writer.tag(2, WireType.Varint).bool(message.is2FaEnabled);
        /* bool allowMarketing = 3; */
        if (message.allowMarketing !== false)
            writer.tag(3, WireType.Varint).bool(message.allowMarketing);
        /* bool isParagraphCommentsEnabled = 4; */
        if (message.isParagraphCommentsEnabled !== false)
            writer.tag(4, WireType.Varint).bool(message.isParagraphCommentsEnabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserSettings
 */
export const UserSettings = new UserSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserPermissions$Type extends MessageType<UserPermissions> {
    constructor() {
        super("wuxiaworld.api.v2.UserPermissions", [
            { no: 1, name: "roles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Role },
            { no: 2, name: "objects", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ObjectItem }
        ]);
    }
    create(value?: PartialMessage<UserPermissions>): UserPermissions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roles = [];
        message.objects = [];
        if (value !== undefined)
            reflectionMergePartial<UserPermissions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserPermissions): UserPermissions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.Role roles */ 1:
                    message.roles.push(Role.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated wuxiaworld.api.v2.ObjectItem objects */ 2:
                    message.objects.push(ObjectItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserPermissions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.Role roles = 1; */
        for (let i = 0; i < message.roles.length; i++)
            Role.internalBinaryWrite(message.roles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated wuxiaworld.api.v2.ObjectItem objects = 2; */
        for (let i = 0; i < message.objects.length; i++)
            ObjectItem.internalBinaryWrite(message.objects[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserPermissions
 */
export const UserPermissions = new UserPermissions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserSponsorInfo$Type extends MessageType<UserSponsorInfo> {
    constructor() {
        super("wuxiaworld.api.v2.UserSponsorInfo", [
            { no: 1, name: "totalCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "activeCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<UserSponsorInfo>): UserSponsorInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalCount = 0;
        message.activeCount = 0;
        if (value !== undefined)
            reflectionMergePartial<UserSponsorInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserSponsorInfo): UserSponsorInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 totalCount */ 1:
                    message.totalCount = reader.int32();
                    break;
                case /* int32 activeCount */ 2:
                    message.activeCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserSponsorInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 totalCount = 1; */
        if (message.totalCount !== 0)
            writer.tag(1, WireType.Varint).int32(message.totalCount);
        /* int32 activeCount = 2; */
        if (message.activeCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.activeCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserSponsorInfo
 */
export const UserSponsorInfo = new UserSponsorInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserVipInfo$Type extends MessageType<UserVipInfo> {
    constructor() {
        super("wuxiaworld.api.v2.UserVipInfo", [
            { no: 1, name: "unlockedNovels", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => UnlockedVipNovelInfo }
        ]);
    }
    create(value?: PartialMessage<UserVipInfo>): UserVipInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.unlockedNovels = [];
        if (value !== undefined)
            reflectionMergePartial<UserVipInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserVipInfo): UserVipInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wuxiaworld.api.v2.UnlockedVipNovelInfo unlockedNovels */ 1:
                    message.unlockedNovels.push(UnlockedVipNovelInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserVipInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wuxiaworld.api.v2.UnlockedVipNovelInfo unlockedNovels = 1; */
        for (let i = 0; i < message.unlockedNovels.length; i++)
            UnlockedVipNovelInfo.internalBinaryWrite(message.unlockedNovels[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserVipInfo
 */
export const UserVipInfo = new UserVipInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserItem$Type extends MessageType<UserItem> {
    constructor() {
        super("wuxiaworld.api.v2.UserItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "userName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "avatarUrl", kind: "message", T: () => StringValue },
            { no: 4, name: "email", kind: "message", T: () => StringValue },
            { no: 5, name: "joinDate", kind: "message", T: () => Timestamp },
            { no: 6, name: "isVipActive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "vip", kind: "message", T: () => VipItem },
            { no: 8, name: "flair", kind: "message", T: () => StringValue },
            { no: 9, name: "settings", kind: "message", T: () => UserSettings },
            { no: 10, name: "permissions", kind: "message", T: () => UserPermissions },
            { no: 11, name: "isLegacy", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "isLegacyVip", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "isEmailVerified", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "sponsorInfo", kind: "message", T: () => UserSponsorInfo },
            { no: 15, name: "vipInfo", kind: "message", T: () => UserVipInfo }
        ]);
    }
    create(value?: PartialMessage<UserItem>): UserItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userName = "";
        message.isVipActive = false;
        message.isLegacy = false;
        message.isLegacyVip = false;
        message.isEmailVerified = false;
        if (value !== undefined)
            reflectionMergePartial<UserItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserItem): UserItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string userName */ 2:
                    message.userName = reader.string();
                    break;
                case /* google.protobuf.StringValue avatarUrl */ 3:
                    message.avatarUrl = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.avatarUrl);
                    break;
                case /* google.protobuf.StringValue email */ 4:
                    message.email = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.email);
                    break;
                case /* google.protobuf.Timestamp joinDate */ 5:
                    message.joinDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.joinDate);
                    break;
                case /* bool isVipActive */ 6:
                    message.isVipActive = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.VipItem vip */ 7:
                    message.vip = VipItem.internalBinaryRead(reader, reader.uint32(), options, message.vip);
                    break;
                case /* google.protobuf.StringValue flair */ 8:
                    message.flair = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.flair);
                    break;
                case /* wuxiaworld.api.v2.UserSettings settings */ 9:
                    message.settings = UserSettings.internalBinaryRead(reader, reader.uint32(), options, message.settings);
                    break;
                case /* wuxiaworld.api.v2.UserPermissions permissions */ 10:
                    message.permissions = UserPermissions.internalBinaryRead(reader, reader.uint32(), options, message.permissions);
                    break;
                case /* bool isLegacy */ 11:
                    message.isLegacy = reader.bool();
                    break;
                case /* bool isLegacyVip */ 12:
                    message.isLegacyVip = reader.bool();
                    break;
                case /* bool isEmailVerified */ 13:
                    message.isEmailVerified = reader.bool();
                    break;
                case /* wuxiaworld.api.v2.UserSponsorInfo sponsorInfo */ 14:
                    message.sponsorInfo = UserSponsorInfo.internalBinaryRead(reader, reader.uint32(), options, message.sponsorInfo);
                    break;
                case /* wuxiaworld.api.v2.UserVipInfo vipInfo */ 15:
                    message.vipInfo = UserVipInfo.internalBinaryRead(reader, reader.uint32(), options, message.vipInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string userName = 2; */
        if (message.userName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userName);
        /* google.protobuf.StringValue avatarUrl = 3; */
        if (message.avatarUrl)
            StringValue.internalBinaryWrite(message.avatarUrl, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue email = 4; */
        if (message.email)
            StringValue.internalBinaryWrite(message.email, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp joinDate = 5; */
        if (message.joinDate)
            Timestamp.internalBinaryWrite(message.joinDate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* bool isVipActive = 6; */
        if (message.isVipActive !== false)
            writer.tag(6, WireType.Varint).bool(message.isVipActive);
        /* wuxiaworld.api.v2.VipItem vip = 7; */
        if (message.vip)
            VipItem.internalBinaryWrite(message.vip, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue flair = 8; */
        if (message.flair)
            StringValue.internalBinaryWrite(message.flair, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.UserSettings settings = 9; */
        if (message.settings)
            UserSettings.internalBinaryWrite(message.settings, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.UserPermissions permissions = 10; */
        if (message.permissions)
            UserPermissions.internalBinaryWrite(message.permissions, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* bool isLegacy = 11; */
        if (message.isLegacy !== false)
            writer.tag(11, WireType.Varint).bool(message.isLegacy);
        /* bool isLegacyVip = 12; */
        if (message.isLegacyVip !== false)
            writer.tag(12, WireType.Varint).bool(message.isLegacyVip);
        /* bool isEmailVerified = 13; */
        if (message.isEmailVerified !== false)
            writer.tag(13, WireType.Varint).bool(message.isEmailVerified);
        /* wuxiaworld.api.v2.UserSponsorInfo sponsorInfo = 14; */
        if (message.sponsorInfo)
            UserSponsorInfo.internalBinaryWrite(message.sponsorInfo, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* wuxiaworld.api.v2.UserVipInfo vipInfo = 15; */
        if (message.vipInfo)
            UserVipInfo.internalBinaryWrite(message.vipInfo, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wuxiaworld.api.v2.UserItem
 */
export const UserItem = new UserItem$Type();
/**
 * @generated ServiceType for protobuf service wuxiaworld.api.v2.Users
 */
export const Users = new ServiceType("wuxiaworld.api.v2.Users", [
    { name: "GetMyUser", options: {}, I: Empty, O: GetMyUserResponse },
    { name: "UpdateUserSettings", options: {}, I: UpdateUserSettingsRequest, O: Empty },
    { name: "SetAvatar", options: {}, I: SetAvatarRequest, O: StringValue },
    { name: "SetAvatarChunked", clientStreaming: true, options: {}, I: SetAvatarChunkedRequest, O: Empty },
    { name: "DeleteAvatar", options: {}, I: Empty, O: Empty },
    { name: "DeleteAccount", options: {}, I: DeleteAccountRequest, O: DeleteAccountResponse }
]);
