name: lncrawl

services:
  server:
    image: lncrawl
    restart: unless-stopped
    ports:
      - "8181:8181"
    command: -ll server -p 8181
    environment:
      - LNCRAWL_DATA_PATH=/data
      - DATABASE_URL=postgresql+psycopg://pguser:pgpass@postgres:5432/lncrawl
    volumes:
      - appdata:/data
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lncrawl
    volumes:
      - pgdata:/var/lib/postgresql/data

  torproxy:
    image: peterdavehello/tor-socks-proxy
    restart: unless-stopped
    ports:
      - "9150:9150" # socks5 port
      - "9151:9151" # control port
    volumes:
      - tor_data:/var/lib/tor
    security_opt:
      - no-new-privileges:true

volumes:
  pgdata:
  appdata:
  tor_data:
