import logging
import os
from typing import Dict, Generator, List, Set

from ..assets.epub import epub_chapter_xhtml, epub_cover_xhtml, epub_style_css
from ..models.chapter import Chapter

try:
    from ebooklib import epub  # type:ignore
except ImportError:
    logging.fatal("Failed to import ebooklib")


logger = logging.getLogger(__name__)

COVER_IMAGE_NAME = "cover.jpg"
STYLE_FILE_NAME = "style.css"
PROJECT_URL = "https://github.com/dipu-bd/lightnovel-crawler"


def bind_epub_book(
    app,
    chapter_groups: List[List[Chapter]],  # chapters grouped by volumes
    images: List[str],  # full path of images to add
    suffix: str,  # suffix to the file name
    book_title: str,
    is_rtl: bool = False,
):
    from ..core.app import App
    assert isinstance(app, App) and app.crawler

    novel_title = app.crawler.novel_title
    novel_author = app.crawler.novel_author or app.crawler.home_url
    novel_url = app.crawler.novel_url
    novel_synopsis = app.crawler.novel_synopsis
    language = app.crawler.language
    novel_tags = app.crawler.novel_tags
    output_path = app.output_path
    book_cover = app.book_cover or app.crawler.novel_cover
    good_file_name = app.good_file_name
    no_suffix_after_filename = app.no_suffix_after_filename

    logger.info("Binding epub for %s", book_title)

    logger.debug("Creating EpubBook instance")
    book = epub.EpubBook()  # type:ignore
    book.set_language(language)
    book.set_title(book_title)
    book.add_author(novel_author)
    book.add_metadata('DC', 'description', novel_synopsis)
    book.set_identifier(output_path + suffix)
    if is_rtl:
        book.set_direction("rtl")

    for tag in novel_tags:
        book.add_metadata("DC", "subject", tag)

    logger.debug("Adding %s", STYLE_FILE_NAME)
    style_item = epub.EpubItem(  # type:ignore
        file_name=STYLE_FILE_NAME,
        content=epub_style_css(),
        media_type="text/css",
    )
    book.add_item(style_item)

    logger.debug("Adding templates")
    book.set_template("cover", epub_cover_xhtml())
    book.set_template("chapter", epub_chapter_xhtml())

    toc = []
    spine = []
    if book_cover and os.path.isfile(book_cover):
        logger.debug("Adding cover image")
        with open(book_cover, "rb") as fp:
            book.set_cover(COVER_IMAGE_NAME, fp.read(), create_page=True)
        spine.append("cover")

        cover_item = epub.EpubHtml(  # type:ignore
            title="Front Page",
            file_name="front.xhtml",
            content=f"""
                <div id="cover">
                    <img src="{COVER_IMAGE_NAME}" alt="cover" />
                </div>
            """,
        )
        cover_item.add_link(
            href=STYLE_FILE_NAME,
            rel="stylesheet",
            type="text/css",
        )
        book.add_item(cover_item)
        spine.append(cover_item)
        toc.append(cover_item)

    logger.debug("Creating intro page")

    intro_html = f"""
    <div id="intro">
        <h1>{novel_title}</h1>
        <h3>{novel_author}</h3>
        <div class="synopsis">
            {novel_synopsis}
        </div>
        <div class="footer">
            <b>Source:</b> <a href="{novel_url}">{novel_url}</a>
            <br>
            <i>Generated by <b>
            <a href="{PROJECT_URL}">Lightnovel Crawler</a></b></i>
        </div>
    </div>
    """
    intro_item = epub.EpubHtml(  # type:ignore
        title="Intro Page",
        file_name="intro.xhtml",
        content=intro_html,
    )
    intro_item.add_link(
        href=STYLE_FILE_NAME,
        rel="stylesheet",
        type="text/css",
    )
    book.add_item(intro_item)
    spine.append(intro_item)
    toc.append(intro_item)

    spine.append("nav")

    logger.debug("Creating chapter contents")
    for chapters in chapter_groups:
        first_chapter = chapters[0]
        volume_id = first_chapter.volume
        volume_title = first_chapter.volume_title or f"Book ${volume_id}"
        volume_html = f"""
        <div id="volume">
            <h1>{volume_title}</h1>
        </div>
        """
        volume_item = epub.EpubHtml(  # type:ignore
            file_name=f"volume_{volume_id}.xhtml",
            content=volume_html,
            title=volume_title,
        )
        volume_item.add_link(
            href=style_item.file_name,
            rel="stylesheet",
            type="text/css",
        )
        book.add_item(volume_item)
        spine.append(volume_item)

        volume_contents = []
        for chapter in chapters:
            chapter_item = epub.EpubHtml(  # type:ignore
                file_name=f"chapter_{chapter.id}.xhtml",
                content=str(chapter["body"]),
                title=chapter["title"],
            )
            chapter_item.add_link(
                href=style_item.file_name,
                rel="stylesheet",
                type="text/css",
            )
            book.add_item(chapter_item)
            spine.append(chapter_item)
            volume_contents.append(chapter_item)

        volume_section = epub.Section(  # type:ignore
            volume_title,
            href=volume_item.file_name
        )
        toc.append([volume_section, volume_contents])

    book.toc = toc
    book.spine = spine
    book.add_item(epub.EpubNcx())  # type:ignore
    book.add_item(epub.EpubNav())  # type:ignore

    logger.debug("Adding images")
    for image_path in images:
        filename = os.path.basename(image_path)
        with open(image_path, "rb") as fp:
            image_item = epub.EpubImage()  # type:ignore
            image_item.file_name = f"images/{filename}"
            image_item.media_type = "image/jpeg"
            image_item.content = fp.read()
        book.add_item(image_item)

    logger.debug("Saving epub file")
    file_name = good_file_name
    if not no_suffix_after_filename:
        file_name += " " + suffix

    epub_path = os.path.join(output_path, "epub")
    file_path = os.path.join(epub_path, file_name + ".epub")

    logger.info("Writing %s", file_path)
    os.makedirs(epub_path, exist_ok=True)
    epub.write_epub(file_path, book, {})  # type:ignore

    logger.info("Created: %s", file_path)
    return file_path


def make_epubs(app, data: Dict[str, List[Chapter]]) -> Generator[str, None, None]:
    from ..core.app import App
    assert isinstance(app, App) and app.crawler

    for volume, chapters in data.items():
        if not chapters:
            continue

        book_title = (app.crawler.novel_title + " " + volume).strip()
        volumes: Dict[int, List[Chapter]] = {}
        for chapter in chapters:
            suffix = chapter.volume or 1
            volumes.setdefault(suffix, []).append(chapter)

        images: Set[str] = set()
        image_path = os.path.join(app.output_path, "images")
        if os.path.isdir(image_path):
            images = set([
                os.path.join(image_path, filename)
                for filename in os.listdir(image_path)
                if filename.endswith(".jpg")
            ])

        yield bind_epub_book(
            app,
            chapter_groups=list(volumes.values()),
            images=list(images),
            suffix=volume,
            book_title=book_title,
        )
