name: lncrawl

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lncrawl
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: lncrawl
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: -ll server -p 8080
    environment:
      - LNCRAWL_DATA_PATH=/data
      - DATABASE_URL=postgresql+psycopg://pguser:pgpass@postgres:5432/lncrawl
    volumes:
      - appdata:/data
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
  appdata:
