// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/custom_pages.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CustomPages } from "./custom_pages";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetCustomPageResponse } from "./custom_pages";
import type { GetCustomPageRequest } from "./custom_pages";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.CustomPages
 */
export interface ICustomPagesClient {
    /**
     * @generated from protobuf rpc: GetCustomPage
     */
    getCustomPage(input: GetCustomPageRequest, options?: RpcOptions): UnaryCall<GetCustomPageRequest, GetCustomPageResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.CustomPages
 */
export class CustomPagesClient implements ICustomPagesClient, ServiceInfo {
    typeName = CustomPages.typeName;
    methods = CustomPages.methods;
    options = CustomPages.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetCustomPage
     */
    getCustomPage(input: GetCustomPageRequest, options?: RpcOptions): UnaryCall<GetCustomPageRequest, GetCustomPageResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCustomPageRequest, GetCustomPageResponse>("unary", this._transport, method, opt, input);
    }
}
