// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/downloads.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Downloads } from "./downloads";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RequestDownloadResponse } from "./downloads";
import type { RequestDownloadRequest } from "./downloads";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.Downloads
 */
export interface IDownloadsClient {
    /**
     * @generated from protobuf rpc: RequestDownload
     */
    requestDownload(input: RequestDownloadRequest, options?: RpcOptions): UnaryCall<RequestDownloadRequest, RequestDownloadResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.Downloads
 */
export class DownloadsClient implements IDownloadsClient, ServiceInfo {
    typeName = Downloads.typeName;
    methods = Downloads.methods;
    options = Downloads.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RequestDownload
     */
    requestDownload(input: RequestDownloadRequest, options?: RpcOptions): UnaryCall<RequestDownloadRequest, RequestDownloadResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RequestDownloadRequest, RequestDownloadResponse>("unary", this._transport, method, opt, input);
    }
}
