// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/ebooks.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Ebooks } from "./ebooks";
import type { GetMyEbooksResponse } from "./ebooks";
import type { Empty } from "../google/protobuf/empty";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetEbooksResponse } from "./ebooks";
import type { GetEbooksRequest } from "./ebooks";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.Ebooks
 */
export interface IEbooksClient {
    /**
     * @generated from protobuf rpc: GetEbooks
     */
    getEbooks(input: GetEbooksRequest, options?: RpcOptions): UnaryCall<GetEbooksRequest, GetEbooksResponse>;
    /**
     * @generated from protobuf rpc: GetMyEbooks
     */
    getMyEbooks(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetMyEbooksResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.Ebooks
 */
export class EbooksClient implements IEbooksClient, ServiceInfo {
    typeName = Ebooks.typeName;
    methods = Ebooks.methods;
    options = Ebooks.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetEbooks
     */
    getEbooks(input: GetEbooksRequest, options?: RpcOptions): UnaryCall<GetEbooksRequest, GetEbooksResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetEbooksRequest, GetEbooksResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyEbooks
     */
    getMyEbooks(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetMyEbooksResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetMyEbooksResponse>("unary", this._transport, method, opt, input);
    }
}
