// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/missions.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Missions } from "./missions";
import type { CompleteMissionResponse } from "./missions";
import type { CompleteMissionRequest } from "./missions";
import type { GetMyCompletedMissionsResponse } from "./missions";
import type { GetMyCompletedMissionsRequest } from "./missions";
import type { GetMyMissionProgressResponse } from "./missions";
import type { GetMyMissionProgressRequest } from "./missions";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetMissionSpecsResponse } from "./missions";
import type { GetMissionSpecsRequest } from "./missions";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.Missions
 */
export interface IMissionsClient {
    /**
     * @generated from protobuf rpc: GetMissionSpecs
     */
    getMissionSpecs(input: GetMissionSpecsRequest, options?: RpcOptions): UnaryCall<GetMissionSpecsRequest, GetMissionSpecsResponse>;
    /**
     * @generated from protobuf rpc: GetMyMissionProgress
     */
    getMyMissionProgress(input: GetMyMissionProgressRequest, options?: RpcOptions): UnaryCall<GetMyMissionProgressRequest, GetMyMissionProgressResponse>;
    /**
     * @generated from protobuf rpc: GetMyCompletedMissions
     */
    getMyCompletedMissions(input: GetMyCompletedMissionsRequest, options?: RpcOptions): UnaryCall<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse>;
    /**
     * @generated from protobuf rpc: CompleteMission
     */
    completeMission(input: CompleteMissionRequest, options?: RpcOptions): UnaryCall<CompleteMissionRequest, CompleteMissionResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.Missions
 */
export class MissionsClient implements IMissionsClient, ServiceInfo {
    typeName = Missions.typeName;
    methods = Missions.methods;
    options = Missions.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetMissionSpecs
     */
    getMissionSpecs(input: GetMissionSpecsRequest, options?: RpcOptions): UnaryCall<GetMissionSpecsRequest, GetMissionSpecsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMissionSpecsRequest, GetMissionSpecsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyMissionProgress
     */
    getMyMissionProgress(input: GetMyMissionProgressRequest, options?: RpcOptions): UnaryCall<GetMyMissionProgressRequest, GetMyMissionProgressResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMyMissionProgressRequest, GetMyMissionProgressResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyCompletedMissions
     */
    getMyCompletedMissions(input: GetMyCompletedMissionsRequest, options?: RpcOptions): UnaryCall<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMyCompletedMissionsRequest, GetMyCompletedMissionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CompleteMission
     */
    completeMission(input: CompleteMissionRequest, options?: RpcOptions): UnaryCall<CompleteMissionRequest, CompleteMissionResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompleteMissionRequest, CompleteMissionResponse>("unary", this._transport, method, opt, input);
    }
}
