// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/product_surveys.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProductSurveys } from "./product_surveys";
import type { AddProductSurveyResponse } from "./product_surveys";
import type { AddProductSurveyRequest } from "./product_surveys";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetProductSurveyForTypeResponse } from "./product_surveys";
import type { GetProductSurveyForTypeRequest } from "./product_surveys";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.ProductSurveys
 */
export interface IProductSurveysClient {
    /**
     * @generated from protobuf rpc: GetProductSurveyForType
     */
    getProductSurveyForType(input: GetProductSurveyForTypeRequest, options?: RpcOptions): UnaryCall<GetProductSurveyForTypeRequest, GetProductSurveyForTypeResponse>;
    /**
     * @generated from protobuf rpc: AddProductSurvey
     */
    addProductSurvey(input: AddProductSurveyRequest, options?: RpcOptions): UnaryCall<AddProductSurveyRequest, AddProductSurveyResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.ProductSurveys
 */
export class ProductSurveysClient implements IProductSurveysClient, ServiceInfo {
    typeName = ProductSurveys.typeName;
    methods = ProductSurveys.methods;
    options = ProductSurveys.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetProductSurveyForType
     */
    getProductSurveyForType(input: GetProductSurveyForTypeRequest, options?: RpcOptions): UnaryCall<GetProductSurveyForTypeRequest, GetProductSurveyForTypeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProductSurveyForTypeRequest, GetProductSurveyForTypeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddProductSurvey
     */
    addProductSurvey(input: AddProductSurveyRequest, options?: RpcOptions): UnaryCall<AddProductSurveyRequest, AddProductSurveyResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddProductSurveyRequest, AddProductSurveyResponse>("unary", this._transport, method, opt, input);
    }
}
