// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number,generate_dependencies
// @generated from protobuf file "Protos/sections.proto" (package "wuxiaworld.api.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Sections } from "./sections";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetSectionResponse } from "./sections";
import type { GetSectionRequest } from "./sections";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service wuxiaworld.api.v2.Sections
 */
export interface ISectionsClient {
    /**
     * @generated from protobuf rpc: GetSection
     */
    getSection(input: GetSectionRequest, options?: RpcOptions): UnaryCall<GetSectionRequest, GetSectionResponse>;
}
/**
 * @generated from protobuf service wuxiaworld.api.v2.Sections
 */
export class SectionsClient implements ISectionsClient, ServiceInfo {
    typeName = Sections.typeName;
    methods = Sections.methods;
    options = Sections.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetSection
     */
    getSection(input: GetSectionRequest, options?: RpcOptions): UnaryCall<GetSectionRequest, GetSectionResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSectionRequest, GetSectionResponse>("unary", this._transport, method, opt, input);
    }
}
