services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lncrawl
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 2G
        reservations:
          cpus: "1.00"
          memory: 1G

  server:
    image: ghcr.io/lncrawl/lightnovel-crawler:latest
    ports:
      - "23457:8080"
    command: -ll server -p 8080
    environment:
      - LNCRAWL_DATA_PATH=/data
      - DATABASE_URL=postgresql+psycopg://pguser:pgpass@postgres:5432/lncrawl
    volumes:
      - ./appdata:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "3.00"
          memory: 5G
        reservations:
          cpus: "2.00"
          memory: 2G
