services:
  server:
    image: ghcr.io/lncrawl/lightnovel-crawler:latest
    ports:
      - "23457:8080"
    command: -ll server -p 8080
    environment:
      - LNCRAWL_DATA_PATH=/data
      - TOR_CONTROL_HOST=torproxy
      - TOR_PROXY_URL=socks5://torproxy:9150
      - DATABASE_URL=postgresql+psycopg://pguser:pgpass@postgres:5432/lncrawl
    volumes:
      - ./appdata:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "3.00"
          memory: "5G"
        reservations:
          cpus: "2.00"
          memory: "512M"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lncrawl
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: "2G"
        reservations:
          memory: "512M"

  torproxy:
    image: peterdavehello/tor-socks-proxy
    restart: unless-stopped
    volumes:
      - tor_data:/var/lib/tor
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          memory: "64M"

volumes:
  tor_data:
