import logging
import re
from pathlib import Path
from threading import Event

from ebooklib import epub  # type: ignore

from ...assets.epub import epub_chapter_xhtml, epub_cover_xhtml, epub_style_css
from ...context import ctx
from ...dao import Artifact, Chapter, Novel, Volume
from ...exceptions import AbortedException

logger = logging.getLogger(__name__)

STYLE_FILE_NAME = "style.css"
COVER_IMAGE_NAME = "cover.jpg"
PROJECT_URL = "https://github.com/lncrawl/lightnovel-crawler"

RE_WHITESPACE = re.compile(r"^\s+|\n", re.MULTILINE)


def build_cover() -> epub.EpubHtml:
    content = RE_WHITESPACE.sub(
        "",
        f"""
        <div id="cover">
            <img src="{COVER_IMAGE_NAME}" alt="cover" />
        </div>
    """,
    )
    item = epub.EpubHtml(
        file_name="front.xhtml",
        title="Front Page",
        content=content,
    )
    item.add_link(
        href=STYLE_FILE_NAME,
        rel="stylesheet",
        type="text/css",
    )
    return item


def build_intro(novel: Novel) -> epub.EpubHtml:
    content = RE_WHITESPACE.sub(
        "",
        f"""
    <div id="intro">
        <h1>{novel.title}</h1>
        <h3>{novel.authors}</h3>
        <div class="synopsis">
            {novel.synopsis}
        </div>
        <div class="footer">
            <b>Source:</b> <a href="{novel.url}">{novel.url}</a>
            <br>
            <i>Generated by <b>
            <a href="{PROJECT_URL}">Lightnovel Crawler</a></b></i>
        </div>
    </div>
    """,
    )
    item = epub.EpubHtml(
        file_name="intro.xhtml",
        title="Intro Page",
        content=content,
    )
    item.add_link(
        href=STYLE_FILE_NAME,
        rel="stylesheet",
        type="text/css",
    )
    return item


def build_volume(volume: Volume) -> epub.EpubHtml:
    content = RE_WHITESPACE.sub(
        "",
        f"""
    <div id="volume">
        <h1>{volume.title}</h1>
    </div>
    """,
    )
    item = epub.EpubHtml(
        file_name=f"volume_{volume.serial:03}.xhtml",
        title=volume.title,
        content=content,
    )
    item.add_link(
        href=STYLE_FILE_NAME,
        rel="stylesheet",
        type="text/css",
    )
    return item


def build_chapter(chapter: Chapter) -> epub.EpubHtml:
    if chapter.is_available:
        text = ctx.files.load_text(chapter.content_file)
    else:
        text = "<p><em>No content available</em></p>"
    content = RE_WHITESPACE.sub(
        "",
        f"""
    <div id="chapter">
        <h4 style="opacity: 0.8">#{chapter.serial}</h4>
        <h1>{chapter.title}</h1>
        {text}
    </div>
    """,
    )
    item = epub.EpubHtml(
        file_name=f"chapter_{chapter.serial:05}.xhtml",
        title=chapter.title,
        content=content,
    )
    item.add_link(
        href=STYLE_FILE_NAME,
        rel="stylesheet",
        type="text/css",
    )
    return item


def make_epub(working_dir: Path, artifact: Artifact, signal=Event(), **kwargs) -> None:
    out_file = ctx.files.resolve(artifact.output_file)
    tmp_file = working_dir / out_file.name

    toc = []
    spine = []
    book = epub.EpubBook()
    novel = ctx.novels.get(artifact.novel_id)

    # add novel metadata
    book.set_identifier(novel.id)
    book.set_title(novel.title)
    if novel.authors:
        book.add_author(novel.authors)
    if novel.language:
        book.set_language(novel.language)
    if novel.synopsis:
        book.add_metadata("DC", "description", novel.synopsis)
    if novel.rtl:
        book.set_direction("rtl")
    for tag in novel.tags:
        book.add_metadata("DC", "subject", tag)

    # add series metadata
    book.add_metadata(None, "meta", "series", {"property": "collection-type"})
    book.add_metadata(None, "meta", novel.title, {"property": "belongs-to-collection"})
    book.add_metadata(None, "meta", str(novel.updated_at), {"property": "group-position"})

    # add template
    book.set_template("cover", epub_cover_xhtml())
    book.set_template("chapter", epub_chapter_xhtml())

    # add style
    style_item = epub.EpubItem(
        file_name=STYLE_FILE_NAME,
        content=epub_style_css(),
        media_type="text/css",
    )
    book.add_item(style_item)

    # add cover image
    if novel.cover_available:
        cover_file = ctx.files.resolve(novel.cover_file)
        book.set_cover(
            COVER_IMAGE_NAME,
            cover_file.read_bytes(),
            create_page=True,
        )
        spine.append("cover")

        # add cover page
        cover_item = build_cover()
        book.add_item(cover_item)
        spine.append(cover_item)
        toc.append(cover_item)

    # add intro page
    intro_item = build_intro(novel)
    book.add_item(intro_item)
    spine.append(intro_item)
    toc.append(intro_item)

    # add nav page
    spine.append("nav")

    # add volumes and chapters pages
    if signal.is_set():
        raise AbortedException()
    for volume in ctx.volumes.list(novel_id=artifact.novel_id):
        if signal.is_set():
            raise AbortedException()

        volume_item = build_volume(volume)
        book.add_item(volume_item)
        spine.append(volume_item)
        volume_contents = []
        for chapter in ctx.chapters.list(volume_id=volume.id):
            if not chapter.is_available:
                continue
            chapter_item = build_chapter(chapter)
            volume_contents.append(chapter_item)
            book.add_item(chapter_item)
            spine.append(chapter_item)

        if not volume_contents:
            continue
        volume_section = epub.Section(volume.title, href=volume_item.file_name)
        toc.append([volume_section, volume_contents])

    # provide table of contents
    book.toc = toc
    book.spine = spine
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # add images
    if signal.is_set():
        raise AbortedException()
    for image in ctx.images.list(novel_id=artifact.novel_id):
        if not image.is_available:
            continue
        image_item = epub.EpubImage(
            file_name=f"images/{image.id}.jpg",
            media_type="image/jpeg",
            content=ctx.files.load(image.image_file),
        )
        book.add_item(image_item)

    # save file
    epub.write_epub(str(tmp_file), book, {})
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.unlink(True)
    tmp_file.rename(out_file)
    logger.info(f"Created: {out_file}")
