name: Update Submodules

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [web-build-updated]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: dev
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔄 Update submodules
        run: git submodule update --force --init --recursive --remote

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: dev
          commit_message: Update submodules
